import re
from typing import Any, Dict, List, Optional

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_tool_update_rules,
    apply_variable_patch,
    build_object_from_mapping,
    compact_dict,
    deep_get,
    extract_by_patterns,
    format_missing_fields,
    get_missing_paths,
    matches_any,
    normalize_text,
    normalize_digits,
    render_template
)


class BookingSubagent:
    """
    Booking executor for the LangGraph architecture.

    Responsibilities:
    - maintain booking state
    - extract deterministic fields
    - resolve slot selection
    - call list_available_slots
    - call create_booking only after explicit confirmation and required details
    - protect against duplicate booking
    - filter slots by service_needed when known

    Not responsible for final customer-facing wording.
    Final wording is generated by graph.response_node and validated by quality_guard.
    """

    name = "booking"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return assistant_config.get("subagents", {}).get(self.name, {})

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {})
        observations: List[Dict[str, Any]] = []
        tool_calls_used = 0

        stage_path = config.get("stage_path", "booking.stage")
        stage = deep_get(variables, stage_path, "")

        if self.is_booking_completed(variables):
            if self.is_polite_closing(context.user_message, config, normalization):
                answer = render_template(
                    config.get("templates", {}).get(
                        "booking_completed_closing",
                        "BOOKING_COMPLETED_CLOSING"
                    ),
                    {
                        "variables": variables,
                        "message": context.user_message
                    }
                )

                return SubagentResult(
                    handled=True,
                    action="reply",
                    answer=answer,
                    variable_updates=variables,
                    selected_subagent=self.name,
                    observations=observations,
                    tool_calls_used=tool_calls_used,
                    notes="booking already confirmed and user sent closing message"
                )

            if self.looks_like_duplicate_confirmation(context.user_message, config, normalization):
                answer = render_template(
                    config.get("templates", {}).get(
                        "booking_already_confirmed",
                        "BOOKING_ALREADY_CONFIRMED"
                    ),
                    {
                        "variables": variables,
                        "message": context.user_message
                    }
                )

                return SubagentResult(
                    handled=True,
                    action="reply",
                    answer=answer,
                    variable_updates=variables,
                    selected_subagent=self.name,
                    observations=observations,
                    tool_calls_used=tool_calls_used,
                    notes="booking already confirmed; duplicate confirmation blocked"
                )

        date_text = self.extract_date_text(
            message=context.user_message,
            config=config,
            normalization=normalization
        )

        if date_text and self.should_extract_date(context, config, stage):
            variables = apply_variable_patch(
                variables,
                {
                    config.get("date_text_path", "date_text"): date_text
                },
                []
            )

        extraction_active_stages = config.get("extraction_active_stages", [
            config.get("stages", {}).get("awaiting_customer_details", "awaiting_customer_details")
        ])

        should_extract_customer_details = stage in extraction_active_stages
        extracted: Dict[str, Any] = {}

        if should_extract_customer_details:
            extracted = extract_by_patterns(
                message=context.user_message,
                patterns=config.get("extraction_patterns", []),
                variables=variables,
                normalization_config=normalization
            )

            if extracted:
                extracted = self.post_process_extracted_fields(extracted, normalization)
                variables = apply_variable_patch(variables, extracted, [])

        stage = deep_get(variables, stage_path, stage)

        if stage == config.get("stages", {}).get("awaiting_confirmation", "awaiting_confirmation"):
            return self.handle_awaiting_confirmation(
                context=context,
                config=config,
                variables=variables,
                observations=observations,
                tool_calls_used=tool_calls_used
            )

        if stage == config.get("stages", {}).get("awaiting_customer_details", "awaiting_customer_details"):
            return self.handle_awaiting_customer_details(
                context=context,
                config=config,
                variables=variables,
                observations=observations,
                tool_calls_used=tool_calls_used
            )

        selected_slot = self.resolve_slot_selection(
            context=context,
            config=config,
            variables=variables
        )

        if selected_slot:
            return self.handle_slot_selected(
                context=context,
                config=config,
                variables=variables,
                selected_slot=selected_slot
            )

        if stage == "slot_selection":
            if self.is_new_availability_request(
                context=context,
                config=config,
                variables=variables
            ):
                return self.handle_booking_request(
                    context=context,
                    config=config,
                    variables=variables,
                    observations=observations,
                    tool_calls_used=tool_calls_used
                )

            answer = render_template(
                config.get("templates", {}).get("choose_slot_again", "BOOKING_SLOT_SELECTION_UNCLEAR"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="slot_selection unresolved"
            )

        if self.is_booking_or_availability_request(
            context=context,
            config=config,
            variables=variables
        ):
            return self.handle_booking_request(
                context=context,
                config=config,
                variables=variables,
                observations=observations,
                tool_calls_used=tool_calls_used
            )

        if extracted:
            return SubagentResult(
                handled=False,
                variable_updates=variables,
                selected_subagent=self.name,
                notes="customer detail extraction only"
            )

        return SubagentResult(handled=False)

    def handle_awaiting_confirmation(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        normalization = context.assistant_config.get("normalization", {})
        confirmation_phrases = config.get("confirmation_phrases", [])
        rejection_phrases = config.get("rejection_phrases", [])

        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="booking already confirmed; create_booking blocked"
            )

        if matches_any(context.user_message, rejection_phrases, normalization):
            updates = config.get("on_reject_updates", {})
            clear = config.get("on_reject_clear", [])

            patched = apply_variable_patch(
                variables,
                updates if isinstance(updates, dict) else {},
                clear if isinstance(clear, list) else []
            )

            answer = render_template(
                config.get("templates", {}).get("slot_rejected", "BOOKING_SLOT_REJECTED"),
                {
                    "variables": patched,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=patched,
                clear_variables=[],
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="pending booking rejected"
            )

        if not matches_any(context.user_message, confirmation_phrases, normalization):
            answer = render_template(
                config.get("templates", {}).get(
                    "repeat_confirmation",
                    "BOOKING_AWAITING_EXPLICIT_CONFIRMATION"
                ),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="awaiting explicit confirmation"
            )

        variables = apply_variable_patch(
            variables,
            config.get("on_confirm_updates", {}),
            []
        )

        missing = get_missing_paths(
            config.get("required_before_create", []),
            variables
        )

        if missing:
            answer = self.render_missing_question(config, variables, missing, context.user_message)

            variables = apply_variable_patch(
                variables,
                config.get("on_missing_details_updates", {}),
                []
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="confirmed slot but missing customer details"
            )

        return self.call_create_booking(
            context=context,
            config=config,
            variables=variables,
            observations=observations,
            tool_calls_used=tool_calls_used
        )

    def handle_awaiting_customer_details(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="booking already confirmed; customer details ignored"
            )

        missing = get_missing_paths(
            config.get("required_before_create", []),
            variables
        )

        if missing:
            answer = self.render_missing_question(config, variables, missing, context.user_message)

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="still missing customer details"
            )

        return self.call_create_booking(
            context=context,
            config=config,
            variables=variables,
            observations=observations,
            tool_calls_used=tool_calls_used
        )

    def handle_slot_selected(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        selected_slot: Dict[str, Any]
    ) -> SubagentResult:
        slot_mapping = config.get("slot_to_pending_booking_mapping", {})
        pending_booking_path = config.get("pending_booking_path", "booking.pending")

        pending = build_object_from_mapping(slot_mapping, {
            "variables": variables,
            "slot": selected_slot,
            "message": context.user_message
        })

        updates = dict(config.get("on_slot_selected_updates", {}))
        updates[pending_booking_path] = pending

        patched = apply_variable_patch(variables, updates, [])

        answer = render_template(
            config.get("templates", {}).get("confirm_slot", "BOOKING_CONFIRM_SELECTED_SLOT"),
            {
                "variables": patched,
                "slot": selected_slot,
                "pending": pending,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="ask_user",
            answer=answer,
            variable_updates=patched,
            clear_variables=config.get("on_slot_selected_clear", []),
            selected_subagent=self.name,
            notes="slot selected"
        )

    def handle_booking_request(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="booking already confirmed; new booking request blocked"
            )

        required_for_slots = config.get("required_before_list_slots", [])
        missing = get_missing_paths(required_for_slots, variables)

        if missing:
            variables = apply_variable_patch(
                variables,
                config.get("on_missing_list_slots_updates", {}),
                []
            )

            answer = self.render_missing_question(config, variables, missing, context.user_message)

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="booking request missing required inputs"
            )

        operations = config.get("operations", {})
        tool_name = config.get("tool_name", "")
        operation = operations.get("list_slots", "")
        arguments_mapping = config.get("list_slots_arguments", {})

        arguments = build_object_from_mapping(arguments_mapping, {
            "variables": variables,
            "message": context.user_message
        })

        tool_result = context.tool_runner.call(
            tool_name=tool_name,
            operation=operation,
            arguments=compact_dict(arguments)
        )

        tool_result = self.filter_slots_by_service_needed(
            tool_result=tool_result,
            variables=variables
        )

        observations.append({
            "subagent": self.name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        tool_calls_used += 1

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        result_context = {
            "variables": updated_variables,
            "result": tool_result,
            "arguments": arguments,
            "message": context.user_message
        }

        slots_found_path = config.get("slots_found_result_path", "slots_found")
        slots_found = deep_get(tool_result, slots_found_path, False)

        if tool_result.get("ok") is False:
            template = config.get("templates", {}).get("tool_error", "BOOKING_TOOL_ERROR")
        elif slots_found is True:
            template = config.get("templates", {}).get("slots_found", "BOOKING_SLOTS_FOUND")
        else:
            template = config.get("templates", {}).get("no_slots", "BOOKING_NO_SLOTS")

        answer = render_template(template, result_context)

        return SubagentResult(
            handled=True,
            action="reply",
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=tool_calls_used,
            notes="listed slots"
        )

    def call_create_booking(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                observations=observations,
                selected_subagent=self.name,
                tool_calls_used=tool_calls_used,
                notes="create_booking blocked because booking already confirmed"
            )

        operations = config.get("operations", {})
        tool_name = config.get("tool_name", "")
        operation = operations.get("create_booking", "")
        arguments_mapping = config.get("create_booking_arguments", {})

        arguments = build_object_from_mapping(arguments_mapping, {
            "variables": variables,
            "message": context.user_message
        })

        arguments["conversation_id"] = deep_get(variables, "conversation_id", "")
        arguments["user_id"] = deep_get(variables, "user_id", "")

        tool_result = context.tool_runner.call(
            tool_name=tool_name,
            operation=operation,
            arguments=compact_dict(arguments)
        )

        observations.append({
            "subagent": self.name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        tool_calls_used += 1

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        template_key = "booking_confirmed" if tool_result.get("ok") is True else "booking_failed"

        answer = render_template(
            config.get("templates", {}).get(template_key, template_key.upper()),
            {
                "variables": updated_variables,
                "result": tool_result,
                "arguments": arguments,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="reply",
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=tool_calls_used,
            notes="create booking attempted"
        )

    def resolve_slot_selection(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]:
        slots_path = config.get("available_slots_path", "available_slots")
        slots = deep_get(variables, slots_path, [])

        if not isinstance(slots, list) or not slots:
            return None

        resolver = config.get("slot_resolver", {})
        normalization = context.assistant_config.get("normalization", {})
        normalized_message = normalize_text(context.user_message, normalization)

        ordinal_map = resolver.get("ordinal_map", {})

        if isinstance(ordinal_map, dict):
            for phrase, index in ordinal_map.items():
                normalized_phrase = normalize_text(str(phrase), normalization)

                if normalized_phrase and normalized_phrase in normalized_message:
                    try:
                        i = int(index)
                    except Exception:
                        continue

                    if 0 <= i < len(slots) and isinstance(slots[i], dict):
                        return slots[i]

        time_field = resolver.get("time_field")
        time_normalizer = resolver.get("time_normalizer")

        if time_field and time_normalizer == "hour_exact_or_same_hour":
            requested_time = self.extract_time(context.user_message, config, normalization)

            if requested_time:
                for slot in slots:
                    slot_time = self.extract_time(str(deep_get(slot, time_field, "")), config, normalization)

                    if slot_time == requested_time:
                        return slot

                requested_hour = requested_time.split(":")[0]

                for slot in slots:
                    slot_time = self.extract_time(str(deep_get(slot, time_field, "")), config, normalization)

                    if slot_time and slot_time.split(":")[0] == requested_hour:
                        return slot

        return None

    def extract_time(self, text: str, config: Dict[str, Any], normalization: Dict[str, Any]) -> str:
        time_config = config.get("time_normalization", {})
        digit_map = normalization.get("digit_map", {})

        raw_text = str(text or "")

        for src, dst in time_config.get("replacements", {}).items():
            raw_text = raw_text.replace(src, dst)

        for src, dst in digit_map.items():
            raw_text = raw_text.replace(src, dst)

        normalized = normalize_text(raw_text, normalization)
        normalized = self.replace_arabic_time_words(normalized)

        regex = time_config.get("regex", r"(\d{1,2})(?::(\d{2}))?\s*(am|pm)?")

        try:
            match = re.search(regex, normalized, flags=re.IGNORECASE)
        except re.error:
            return ""

        if not match:
            return ""

        hour = int(match.group(1))
        minute = int(match.group(2) or "0")
        suffix = (match.group(3) or "").lower()

        if suffix == "pm" and hour < 12:
            hour += 12

        if suffix == "am" and hour == 12:
            hour = 0

        if hour < 0 or hour > 23 or minute < 0 or minute > 59:
            return ""

        return f"{hour:02d}:{minute:02d}"

    @staticmethod
    def replace_arabic_time_words(text: str) -> str:
        word_map = {
            "واحده": "1",
            "واحد": "1",
            "اتنين": "2",
            "اثنين": "2",
            "تلاته": "3",
            "ثلاثه": "3",
            "اربعه": "4",
            "اربعة": "4",
            "خمسه": "5",
            "خمسة": "5",
            "سته": "6",
            "ستة": "6",
            "سبعه": "7",
            "سبعة": "7",
            "تمانيه": "8",
            "ثمانيه": "8",
            "تسعه": "9",
            "تسعة": "9",
            "عشره": "10",
            "عشر": "10",
            "احداشر": "11",
            "حداشر": "11",
            "احدي عشر": "11",
            "اتناشر": "12",
            "اتني عشر": "12",
            "اثني عشر": "12"
        }

        output = text

        for word, number in sorted(word_map.items(), key=lambda item: len(item[0]), reverse=True):
            output = re.sub(rf"\b{re.escape(word)}\b", number, output)

        return output

    def should_extract_date(self, context: SubagentContext, config: Dict[str, Any], stage: str) -> bool:
        active_stages = config.get("active_request_stages", [])

        if stage in active_stages:
            return True

        return matches_any(
            context.user_message,
            config.get("trigger_phrases", []),
            context.assistant_config.get("normalization", {})
        )

    def extract_date_text(self, message: str, config: Dict[str, Any], normalization: Dict[str, Any]) -> str:
        raw_message = normalize_digits(str(message or ""), normalization.get("digit_map", {})).strip()
        normalized = normalize_text(raw_message, normalization)

        for item in config.get("date_extraction_patterns", []):
            if not isinstance(item, dict):
                continue

            regex = item.get("regex", "")
            group = int(item.get("group", 1))

            if not regex:
                continue

            try:
                match = re.search(regex, raw_message, flags=re.IGNORECASE)
            except re.error:
                continue

            if match:
                value = match.group(group).strip()
                if value:
                    return value

        direct_terms = config.get("date_direct_terms", [])

        for term in direct_terms:
            normalized_term = normalize_text(str(term), normalization)

            if normalized_term and normalized_term in normalized:
                return str(term)

        return ""

    def is_booking_or_availability_request(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        normalization = context.assistant_config.get("normalization", {})
        phrases = config.get("trigger_phrases", [])

        if matches_any(context.user_message, phrases, normalization):
            return True

        stage_path = config.get("stage_path", "booking.stage")
        stage = deep_get(variables, stage_path, "")

        return stage in config.get("active_request_stages", [])

    def is_new_availability_request(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        normalization = context.assistant_config.get("normalization", {})
        message = normalize_text(context.user_message, normalization)

        availability_terms = config.get("availability_request_terms", [])

        if not isinstance(availability_terms, list):
            availability_terms = []

        has_availability_intent = any(
            normalize_text(term, normalization) in message
            for term in availability_terms
            if str(term or "").strip()
        )

        if not has_availability_intent:
            return False

        branch = deep_get(variables, "selected_branch") or deep_get(variables, "location_branch")
        date_text = deep_get(variables, config.get("date_text_path", "date_text"))

        return bool(branch and date_text)

    def render_missing_question(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        missing: List[str],
        message: str
    ) -> str:
        templates = config.get("templates", {})
        missing_set = set(missing)

        template_key = "missing_fields"

        if missing_set == {"variables.date_text"}:
            template_key = "missing_date"
        elif missing_set == {"variables.selected_branch"}:
            template_key = "missing_branch"
        elif missing_set == {"variables.customer_profile.full_name"}:
            template_key = "missing_full_name"
        elif missing_set == {"variables.customer_profile.plate_number"}:
            template_key = "missing_plate_number"
        elif missing_set == {
            "variables.customer_profile.full_name",
            "variables.customer_profile.plate_number"
        }:
            template_key = "missing_name_and_plate"

        labels = config.get("field_labels", {})
        missing_text = format_missing_fields(missing, labels)

        return render_template(
            templates.get(template_key, templates.get("missing_fields", "BOOKING_MISSING_FIELDS")),
            {
                "variables": variables,
                "missing_fields": missing_text,
                "missing_paths": missing,
                "message": message
            }
        )

    def filter_slots_by_service_needed(
        self,
        tool_result: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> Dict[str, Any]:
        if not isinstance(tool_result, dict):
            return tool_result

        service_needed = str(deep_get(variables, "service_needed") or "").strip()

        if not service_needed:
            return tool_result

        slots = tool_result.get("available_slots")

        if not isinstance(slots, list):
            return tool_result

        service_norm = self.norm_section(service_needed)

        filtered = [
            slot for slot in slots
            if isinstance(slot, dict)
            and self.norm_section(str(slot.get("section") or "")) == service_norm
        ]

        patched = dict(tool_result)
        patched["available_slots"] = filtered
        patched["slots_found"] = len(filtered) > 0

        if filtered:
            patched["available_slots_text"] = self.render_slots_text(filtered)
        else:
            patched["available_slots_text"] = ""

        return patched

    def render_slots_text(self, slots: List[Dict[str, Any]]) -> str:
        lines = []

        for index, slot in enumerate(slots, 1):
            time = str(slot.get("time") or "").strip()
            section = str(slot.get("section") or "").strip()
            remaining = (
                slot.get("remaining_capacity")
                if slot.get("remaining_capacity") is not None
                else slot.get("places_left")
            )

            parts = [f"{index})"]

            if time:
                parts.append(time)

            if section:
                parts.append(section)

            if remaining is not None and str(remaining).strip() != "":
                parts.append(f"remaining={remaining}")

            lines.append(" - ".join(parts))

        return "\n".join(lines)

    def is_booking_completed(self, variables: Dict[str, Any]) -> bool:
        status = str(deep_get(variables, "booking_status") or "").lower()
        stage = str(deep_get(variables, "booking.stage") or "").lower()
        visit_id = deep_get(variables, "visit_id")

        return bool(
            visit_id
            or status in {"confirmed", "booking_confirmed", "booked"}
            or stage in {"confirmed", "booking_confirmed", "booked"}
        )

    def is_polite_closing(
        self,
        message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        terms = config.get("closing_phrases", [
            "شكرا",
            "شكرًا",
            "متشكر",
            "تمام شكرا",
            "تمام شكرًا",
            "تسلم",
            "thanks",
            "thank you"
        ])

        return matches_any(message, terms, normalization)

    def looks_like_duplicate_confirmation(
        self,
        message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        duplicate_terms = config.get("duplicate_confirmation_phrases", [])
        confirmation_terms = config.get("confirmation_phrases", [])

        return (
            matches_any(message, duplicate_terms, normalization)
            or matches_any(message, confirmation_terms, normalization)
        )

    def post_process_extracted_fields(
        self,
        extracted: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        output = dict(extracted)

        plate = output.get("customer_profile.plate_number")

        if plate:
            output["customer_profile.plate_number"] = self.normalize_plate_number(
                str(plate),
                normalization
            )

        full_name = output.get("customer_profile.full_name")

        if full_name:
            output["customer_profile.full_name"] = re.sub(
                r"\s+",
                " ",
                str(full_name).strip()
            )

        return output

    @staticmethod
    def norm_section(value: str) -> str:
        return re.sub(r"\s+", " ", str(value or "").strip().lower())

    @staticmethod
    def normalize_plate_number(value: str, normalization: Dict[str, Any]) -> str:
        digit_map = normalization.get("digit_map", {})
        text = str(value or "")

        for src, dst in digit_map.items():
            text = text.replace(src, dst)

        text = re.sub(r"[،,.!?؟:;]+", " ", text)
        text = re.sub(r"\s+", " ", text).strip()

        return text
