import re
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from app.config import TZ
from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_tool_update_rules,
    apply_variable_patch,
    build_object_from_mapping,
    compact_dict,
    deep_get,
    extract_by_patterns,
    format_missing_fields,
    get_missing_paths,
    get_subagent_config,
    matches_any,
    normalize_text,
    normalize_digits,
    render_template
)


class BookingSubagent:
    """
    Booking executor for the LangGraph architecture.

    Responsibilities:
    - maintain booking state
    - extract deterministic fields
    - resolve canonical branch from stored branch state or configured branch aliases
    - resolve normalized appointment dates from natural date phrases
    - resolve slot selection
    - collect customer details without asking repeatedly for already captured fields
    - call list_available_slots
    - call create_booking only after explicit confirmation and required details
    - protect against duplicate booking
    - filter slots by service_needed when known

    Not responsible for final customer-facing wording.
    Final wording is generated by graph.response_node and validated by quality_guard.
    """

    name = "booking"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {})
        variables = self.ensure_valid_customer_profile(
            variables=variables,
            message=context.user_message,
            normalization=normalization
        )
        observations: List[Dict[str, Any]] = []
        tool_calls_used = 0

        stage_path = config.get("stage_path", "booking.stage")
        stage = deep_get(variables, stage_path, "")

        variables = self.ensure_selected_branch_from_context(
            variables=variables,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        # Critical slot-selection guard:
        # In slot_selection stage, a message like "الساعة 12" or "معاد 12"
        # must be resolved against the existing available_slots before any
        # date extraction runs. Otherwise it can be misclassified as date_text.
        if stage == "slot_selection":
            selected_slot_before_date = self.resolve_slot_selection(
                context=context,
                config=config,
                variables=variables
            )

            if selected_slot_before_date:
                return self.handle_slot_selected(
                    context=context,
                    config=config,
                    variables=variables,
                    selected_slot=selected_slot_before_date
                )

        if self.is_booking_completed(variables):
            if self.is_polite_closing(context.user_message, config, normalization):
                answer = render_template(
                    config.get("templates", {}).get(
                        "booking_completed_closing",
                        "BOOKING_COMPLETED_CLOSING"
                    ),
                    {
                        "variables": variables,
                        "message": context.user_message
                    }
                )

                return SubagentResult(
                    handled=True,
                    action="reply",
                    answer=answer,
                    variable_updates=variables,
                    selected_subagent=self.name,
                    observations=observations,
                    tool_calls_used=tool_calls_used,
                    notes="booking already confirmed and user sent closing message"
                )

            if self.looks_like_duplicate_confirmation(context.user_message, config, normalization):
                answer = render_template(
                    config.get("templates", {}).get(
                        "booking_already_confirmed",
                        "BOOKING_ALREADY_CONFIRMED"
                    ),
                    {
                        "variables": variables,
                        "message": context.user_message
                    }
                )

                return SubagentResult(
                    handled=True,
                    action="reply",
                    answer=answer,
                    variable_updates=variables,
                    selected_subagent=self.name,
                    observations=observations,
                    tool_calls_used=tool_calls_used,
                    notes="booking already confirmed; duplicate confirmation blocked"
                )

        date_text = self.extract_date_text(
            message=context.user_message,
            config=config,
            normalization=normalization
        )

        if date_text and self.should_extract_date(context, config, stage):
            date_updates = {
                config.get("date_text_path", "date_text"): date_text
            }

            resolved_date = self.resolve_date_text(
                date_text=date_text,
                message=context.user_message,
                normalization=normalization
            )

            if resolved_date:
                date_updates[config.get("appointment_date_path", "appointment_date")] = resolved_date
                date_updates["date"] = resolved_date

            variables = apply_variable_patch(
                variables,
                date_updates,
                []
            )

        variables = self.ensure_resolved_date_from_existing_state(
            variables=variables,
            config=config,
            normalization=normalization,
            message=context.user_message
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        extraction_active_stages = config.get("extraction_active_stages", [
            config.get("stages", {}).get("awaiting_customer_details", "awaiting_customer_details")
        ])

        should_extract_customer_details = stage in extraction_active_stages
        extracted: Dict[str, Any] = {}

        if should_extract_customer_details:
            extracted = self.extract_customer_details(
                message=context.user_message,
                config=config,
                variables=variables,
                normalization=normalization
            )

            if extracted:
                variables = apply_variable_patch(variables, extracted, [])

            variables = self.ensure_valid_customer_profile(
                variables=variables,
                message=context.user_message,
                normalization=normalization
            )

        stage = deep_get(variables, stage_path, stage)

        if stage == config.get("stages", {}).get("awaiting_confirmation", "awaiting_confirmation"):
            return self.handle_awaiting_confirmation(
                context=context,
                config=config,
                variables=variables,
                observations=observations,
                tool_calls_used=tool_calls_used
            )

        if stage == config.get("stages", {}).get("awaiting_customer_details", "awaiting_customer_details"):
            return self.handle_awaiting_customer_details(
                context=context,
                config=config,
                variables=variables,
                observations=observations,
                tool_calls_used=tool_calls_used
            )

        selected_slot = self.resolve_slot_selection(
            context=context,
            config=config,
            variables=variables
        )

        if selected_slot:
            return self.handle_slot_selected(
                context=context,
                config=config,
                variables=variables,
                selected_slot=selected_slot
            )

        if stage == "slot_selection":
            if self.is_new_availability_request(
                context=context,
                config=config,
                variables=variables
            ):
                return self.handle_booking_request(
                    context=context,
                    config=config,
                    variables=variables,
                    observations=observations,
                    tool_calls_used=tool_calls_used
                )

            answer = render_template(
                config.get("templates", {}).get("choose_slot_again", "BOOKING_SLOT_SELECTION_UNCLEAR"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="slot_selection unresolved"
            )

        if self.is_booking_or_availability_request(
            context=context,
            config=config,
            variables=variables
        ):
            return self.handle_booking_request(
                context=context,
                config=config,
                variables=variables,
                observations=observations,
                tool_calls_used=tool_calls_used
            )

        if extracted:
            return SubagentResult(
                handled=False,
                variable_updates=variables,
                selected_subagent=self.name,
                notes="customer detail extraction only"
            )

        return SubagentResult(handled=False)

    def handle_awaiting_confirmation(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        normalization = context.assistant_config.get("normalization", {})
        confirmation_phrases = config.get("confirmation_phrases", [])
        rejection_phrases = config.get("rejection_phrases", [])

        variables = self.ensure_selected_branch_from_context(
            variables=variables,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="booking already confirmed; create_booking blocked"
            )

        if matches_any(context.user_message, rejection_phrases, normalization):
            updates = config.get("on_reject_updates", {})
            clear = config.get("on_reject_clear", [])

            patched = apply_variable_patch(
                variables,
                updates if isinstance(updates, dict) else {},
                clear if isinstance(clear, list) else []
            )

            answer = render_template(
                config.get("templates", {}).get("slot_rejected", "BOOKING_SLOT_REJECTED"),
                {
                    "variables": patched,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=patched,
                clear_variables=[],
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="pending booking rejected"
            )

        # In confirmation stage, do not allow generic extraction to treat
        # confirmation-only replies like "اه اكده تمام" as a customer name.
        details: Dict[str, Any] = {}

        if self.has_customer_detail_signal(context.user_message, normalization):
            details = self.extract_customer_details(
                message=context.user_message,
                config=config,
                variables=variables,
                normalization=normalization
            )

            if details:
                variables = apply_variable_patch(variables, details, [])

        variables = self.ensure_valid_customer_profile(
            variables=variables,
            message=context.user_message,
            normalization=normalization
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        if not matches_any(context.user_message, confirmation_phrases, normalization):
            answer = render_template(
                config.get("templates", {}).get(
                    "repeat_confirmation",
                    "BOOKING_AWAITING_EXPLICIT_CONFIRMATION"
                ),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="awaiting explicit confirmation"
            )

        variables = apply_variable_patch(
            variables,
            config.get("on_confirm_updates", {}),
            []
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        missing = self.get_missing_required_create_fields(config, variables)

        if missing:
            answer = self.render_missing_question(config, variables, missing, context.user_message)

            variables = apply_variable_patch(
                variables,
                config.get("on_missing_details_updates", {}),
                []
            )

            variables = self.ensure_pending_booking_context(
                variables=variables,
                config=config,
                assistant_config=context.assistant_config,
                message=context.user_message,
                normalization=normalization
            )

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes=f"confirmed slot but missing customer details: {missing}"
            )

        return self.call_create_booking(
            context=context,
            config=config,
            variables=variables,
            observations=observations,
            tool_calls_used=tool_calls_used
        )


    def handle_awaiting_customer_details(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        normalization = context.assistant_config.get("normalization", {})

        variables = self.ensure_selected_branch_from_context(
            variables=variables,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="booking already confirmed; customer details ignored"
            )

        details = self.extract_customer_details(
            message=context.user_message,
            config=config,
            variables=variables,
            normalization=normalization
        )

        if details:
            variables = apply_variable_patch(variables, details, [])

        variables = self.ensure_valid_customer_profile(
            variables=variables,
            message=context.user_message,
            normalization=normalization
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        missing = self.get_missing_required_create_fields(config, variables)

        if missing:
            answer = self.render_missing_question(config, variables, missing, context.user_message)

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes=f"still missing customer details after extraction: {missing}"
            )

        return self.call_create_booking(
            context=context,
            config=config,
            variables=variables,
            observations=observations,
            tool_calls_used=tool_calls_used
        )


    def handle_slot_selected(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        selected_slot: Dict[str, Any]
    ) -> SubagentResult:
        normalization = context.assistant_config.get("normalization", {})

        variables = self.ensure_selected_branch_from_context(
            variables=variables,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        slot_mapping = config.get("slot_to_pending_booking_mapping", {})
        pending_booking_path = config.get("pending_booking_path", "booking.pending")

        pending = build_object_from_mapping(slot_mapping, {
            "variables": variables,
            "slot": selected_slot,
            "message": context.user_message
        })

        known_branch = self.get_known_branch(variables)

        if pending.get("branch") in [None, ""]:
            pending["branch"] = known_branch

        if pending.get("branch") not in [None, ""]:
            canonical_branch = self.resolve_canonical_branch(
                value=str(pending.get("branch") or ""),
                assistant_config=context.assistant_config,
                normalization=normalization
            )
            if canonical_branch:
                pending["branch"] = canonical_branch

        if pending.get("date") in [None, ""]:
            pending["date"] = (
                deep_get(variables, config.get("appointment_date_path", "appointment_date"))
                or deep_get(variables, "date")
                or pending.get("date_text")
            )

        if pending.get("date_text") in [None, ""]:
            pending["date_text"] = deep_get(variables, config.get("date_text_path", "date_text"), "")

        if pending.get("time") in [None, ""]:
            selected_time = selected_slot.get("time") if isinstance(selected_slot, dict) else ""
            if selected_time:
                pending["time"] = selected_time

        if pending.get("section") in [None, ""]:
            selected_section = selected_slot.get("section") if isinstance(selected_slot, dict) else ""
            if selected_section:
                pending["section"] = selected_section

        updates = dict(config.get("on_slot_selected_updates", {}))
        updates[pending_booking_path] = pending
        updates["booking.pending_summary"] = self.build_pending_summary(pending)

        if pending.get("branch"):
            updates["selected_branch"] = pending.get("branch")
            updates["location_branch"] = pending.get("branch")

            if not deep_get(variables, "nearest_branch"):
                updates["nearest_branch"] = pending.get("branch")

        if pending.get("date"):
            updates[config.get("appointment_date_path", "appointment_date")] = pending.get("date")
            updates["date"] = pending.get("date")

        if pending.get("date_text"):
            updates[config.get("date_text_path", "date_text")] = pending.get("date_text")

        if pending.get("time"):
            updates["appointment_time"] = pending.get("time")

        patched = apply_variable_patch(variables, updates, [])

        answer = render_template(
            config.get("templates", {}).get("confirm_slot", "BOOKING_CONFIRM_SELECTED_SLOT"),
            {
                "variables": patched,
                "slot": selected_slot,
                "pending": pending,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="ask_user",
            answer=answer,
            variable_updates=patched,
            clear_variables=config.get("on_slot_selected_clear", []),
            selected_subagent=self.name,
            notes="slot selected; pending booking prepared with branch/date/time context"
        )


    def handle_booking_request(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes="booking already confirmed; new booking request blocked"
            )

        normalization = context.assistant_config.get("normalization", {})

        variables = self.ensure_selected_branch_from_context(
            variables=variables,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        variables = self.ensure_resolved_date_from_existing_state(
            variables=variables,
            config=config,
            normalization=normalization,
            message=context.user_message
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=normalization
        )

        required_for_slots = config.get("required_before_list_slots", [])
        missing = get_missing_paths(required_for_slots, variables)

        if missing:
            variables = apply_variable_patch(
                variables,
                config.get("on_missing_list_slots_updates", {}),
                []
            )

            answer = self.render_missing_question(config, variables, missing, context.user_message)

            return SubagentResult(
                handled=True,
                action="ask_user",
                answer=answer,
                variable_updates=variables,
                selected_subagent=self.name,
                observations=observations,
                tool_calls_used=tool_calls_used,
                notes=f"booking request missing required inputs: {missing}"
            )

        operations = config.get("operations", {})
        tool_name = config.get("tool_name", "")
        operation = operations.get("list_slots", "")
        arguments_mapping = config.get("list_slots_arguments", {})

        arguments = build_object_from_mapping(arguments_mapping, {
            "variables": variables,
            "message": context.user_message
        })

        appointment_date = (
            deep_get(variables, "booking.pending.date")
            or deep_get(variables, config.get("appointment_date_path", "appointment_date"))
            or deep_get(variables, "date")
        )

        date_text = (
            deep_get(variables, "booking.pending.date_text")
            or deep_get(variables, config.get("date_text_path", "date_text"))
        )

        branch = self.resolve_canonical_branch(
            value=str(arguments.get("branch") or ""),
            assistant_config=context.assistant_config,
            normalization=normalization
        ) or self.get_known_branch(variables)

        if branch:
            arguments["branch"] = branch

        if appointment_date:
            arguments["date"] = appointment_date

        if date_text and not arguments.get("date_text"):
            arguments["date_text"] = date_text

        tool_result = context.tool_runner.call(
            tool_name=tool_name,
            operation=operation,
            arguments=compact_dict(arguments)
        )

        tool_result = self.filter_slots_by_service_needed(
            tool_result=tool_result,
            variables=variables
        )

        observations.append({
            "subagent": self.name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        tool_calls_used += 1

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        repair_updates: Dict[str, Any] = {}

        if branch:
            repair_updates["selected_branch"] = branch
            repair_updates["location_branch"] = branch

        if appointment_date:
            repair_updates[config.get("appointment_date_path", "appointment_date")] = appointment_date
            repair_updates["date"] = appointment_date

        if date_text:
            repair_updates[config.get("date_text_path", "date_text")] = date_text

        if repair_updates:
            updated_variables = apply_variable_patch(updated_variables, repair_updates, [])

        result_context = {
            "variables": updated_variables,
            "result": tool_result,
            "arguments": arguments,
            "message": context.user_message
        }

        slots_found_path = config.get("slots_found_result_path", "slots_found")
        slots_found = deep_get(tool_result, slots_found_path, False)

        if tool_result.get("ok") is False:
            template = config.get("templates", {}).get("tool_error", "BOOKING_TOOL_ERROR")
        elif slots_found is True:
            template = config.get("templates", {}).get("slots_found", "BOOKING_SLOTS_FOUND")
        else:
            template = config.get("templates", {}).get("no_slots", "BOOKING_NO_SLOTS")

        answer = render_template(template, result_context)

        return SubagentResult(
            handled=True,
            action="reply",
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=tool_calls_used,
            notes="listed slots"
        )

    def call_create_booking(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        observations: List[Dict[str, Any]],
        tool_calls_used: int
    ) -> SubagentResult:
        if self.is_booking_completed(variables):
            answer = render_template(
                config.get("templates", {}).get("booking_already_confirmed", "BOOKING_ALREADY_CONFIRMED"),
                {
                    "variables": variables,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action="reply",
                answer=answer,
                variable_updates=variables,
                observations=observations,
                selected_subagent=self.name,
                tool_calls_used=tool_calls_used,
                notes="create_booking blocked because booking already confirmed"
            )

        variables = self.ensure_resolved_date_from_existing_state(
            variables=variables,
            config=config,
            normalization=context.assistant_config.get("normalization", {}),
            message=context.user_message
        )

        variables = self.ensure_selected_branch_from_context(
            variables=variables,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=context.assistant_config.get("normalization", {})
        )

        variables = self.ensure_pending_booking_context(
            variables=variables,
            config=config,
            assistant_config=context.assistant_config,
            message=context.user_message,
            normalization=context.assistant_config.get("normalization", {})
        )

        operations = config.get("operations", {})
        tool_name = config.get("tool_name", "")
        operation = operations.get("create_booking", "")
        arguments_mapping = config.get("create_booking_arguments", {})

        arguments = build_object_from_mapping(arguments_mapping, {
            "variables": variables,
            "message": context.user_message
        })

        appointment_date = (
            deep_get(variables, "booking.pending.date")
            or deep_get(variables, config.get("appointment_date_path", "appointment_date"))
            or deep_get(variables, "date")
        )

        date_text = (
            deep_get(variables, "booking.pending.date_text")
            or deep_get(variables, config.get("date_text_path", "date_text"))
        )

        if appointment_date:
            arguments["date"] = appointment_date

        if date_text and not arguments.get("date_text"):
            arguments["date_text"] = date_text

        branch = self.resolve_canonical_branch(
            value=str(arguments.get("branch") or ""),
            assistant_config=context.assistant_config,
            normalization=context.assistant_config.get("normalization", {})
        ) or self.get_known_branch(variables)

        if branch:
            arguments["branch"] = branch

        arguments["conversation_id"] = deep_get(variables, "conversation_id", "")
        arguments["user_id"] = deep_get(variables, "user_id", "")

        tool_result = context.tool_runner.call(
            tool_name=tool_name,
            operation=operation,
            arguments=compact_dict(arguments)
        )

        observations.append({
            "subagent": self.name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        tool_calls_used += 1

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        repair_updates: Dict[str, Any] = {}

        if branch:
            repair_updates["selected_branch"] = branch
            repair_updates["location_branch"] = branch

        if appointment_date:
            repair_updates[config.get("appointment_date_path", "appointment_date")] = appointment_date
            repair_updates["date"] = appointment_date

        if date_text:
            repair_updates[config.get("date_text_path", "date_text")] = date_text

        if repair_updates:
            updated_variables = apply_variable_patch(updated_variables, repair_updates, [])

        template_key = "booking_confirmed" if tool_result.get("ok") is True else "booking_failed"

        answer = render_template(
            config.get("templates", {}).get(template_key, template_key.upper()),
            {
                "variables": updated_variables,
                "result": tool_result,
                "arguments": arguments,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="reply",
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=tool_calls_used,
            notes="create booking attempted"
        )

    def resolve_slot_selection(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]:
        slots_path = config.get("available_slots_path", "available_slots")
        slots = deep_get(variables, slots_path, [])

        if not isinstance(slots, list) or not slots:
            return None

        resolver = config.get("slot_resolver", {})
        normalization = context.assistant_config.get("normalization", {})
        normalized_message = normalize_text(context.user_message, normalization)

        ordinal_map = resolver.get("ordinal_map", {})

        if isinstance(ordinal_map, dict):
            for phrase, index in ordinal_map.items():
                normalized_phrase = normalize_text(str(phrase), normalization)

                if normalized_phrase and normalized_phrase in normalized_message:
                    try:
                        i = int(index)
                    except Exception:
                        continue

                    if 0 <= i < len(slots) and isinstance(slots[i], dict):
                        return slots[i]

        time_field = resolver.get("time_field")
        time_normalizer = resolver.get("time_normalizer")

        if time_field and time_normalizer == "hour_exact_or_same_hour":
            requested_time = self.extract_time(context.user_message, config, normalization)

            if requested_time:
                for slot in slots:
                    slot_time = self.extract_time(str(deep_get(slot, time_field, "")), config, normalization)

                    if slot_time == requested_time:
                        return slot

                requested_hour = requested_time.split(":")[0]

                for slot in slots:
                    slot_time = self.extract_time(str(deep_get(slot, time_field, "")), config, normalization)

                    if slot_time and slot_time.split(":")[0] == requested_hour:
                        return slot

        return None

    def extract_time(self, text: str, config: Dict[str, Any], normalization: Dict[str, Any]) -> str:
        time_config = config.get("time_normalization", {})
        digit_map = normalization.get("digit_map", {})

        raw_text = str(text or "")

        for src, dst in time_config.get("replacements", {}).items():
            raw_text = raw_text.replace(src, dst)

        for src, dst in digit_map.items():
            raw_text = raw_text.replace(src, dst)

        normalized = normalize_text(raw_text, normalization)
        normalized = self.replace_arabic_time_words(normalized)

        regex = time_config.get("regex", r"(\d{1,2})(?::(\d{2}))?\s*(am|pm)?")

        try:
            match = re.search(regex, normalized, flags=re.IGNORECASE)
        except re.error:
            return ""

        if not match:
            return ""

        hour = int(match.group(1))
        minute = int(match.group(2) or "0")
        suffix = (match.group(3) or "").lower()

        if suffix == "pm" and hour < 12:
            hour += 12

        if suffix == "am" and hour == 12:
            hour = 0

        if hour < 0 or hour > 23 or minute < 0 or minute > 59:
            return ""

        return f"{hour:02d}:{minute:02d}"

    @staticmethod
    def replace_arabic_time_words(text: str) -> str:
        word_map = {
            "واحده": "1",
            "واحد": "1",
            "اتنين": "2",
            "اثنين": "2",
            "تلاته": "3",
            "ثلاثه": "3",
            "اربعه": "4",
            "اربعة": "4",
            "خمسه": "5",
            "خمسة": "5",
            "سته": "6",
            "ستة": "6",
            "سبعه": "7",
            "سبعة": "7",
            "تمانيه": "8",
            "ثمانيه": "8",
            "تسعه": "9",
            "تسعة": "9",
            "عشره": "10",
            "عشر": "10",
            "احداشر": "11",
            "حداشر": "11",
            "احدي عشر": "11",
            "اتناشر": "12",
            "اتني عشر": "12",
            "اثني عشر": "12"
        }

        output = text

        for word, number in sorted(word_map.items(), key=lambda item: len(item[0]), reverse=True):
            output = re.sub(rf"\b{re.escape(word)}\b", number, output)

        return output

    def should_extract_date(self, context: SubagentContext, config: Dict[str, Any], stage: str) -> bool:
        active_stages = config.get("active_request_stages", [])

        if stage in active_stages:
            return True

        return matches_any(
            context.user_message,
            config.get("trigger_phrases", []),
            context.assistant_config.get("normalization", {})
        )

    def extract_date_text(self, message: str, config: Dict[str, Any], normalization: Dict[str, Any]) -> str:
        raw_message = normalize_digits(str(message or ""), normalization.get("digit_map", {})).strip()
        normalized = normalize_text(raw_message, normalization)

        # Do not let time-only slot selections become date_text.
        # Example during slot_selection:
        # "لا معاد الساعة 12 هيكون مناسب معايا اكتر"
        # should resolve to a slot time, not date_text="الساعة 12..."
        if self.looks_like_time_only_slot_selection_text(
            message=raw_message,
            config=config,
            normalization=normalization
        ):
            return ""

        direct = self.extract_direct_date_term(
            normalized_message=normalized,
            config=config,
            normalization=normalization
        )

        if direct:
            return direct

        explicit = self.extract_explicit_date_phrase(raw_message)

        if explicit:
            return explicit

        for item in config.get("date_extraction_patterns", []):
            if not isinstance(item, dict):
                continue

            regex = item.get("regex", "")
            group = int(item.get("group", 1))

            if not regex:
                continue

            try:
                match = re.search(regex, raw_message, flags=re.IGNORECASE)
            except re.error:
                continue

            if match:
                value = self.clean_date_text(match.group(group).strip(), normalization)
                if value:
                    return value

        return ""

    def looks_like_time_only_slot_selection_text(
        self,
        message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        raw_message = str(message or "").strip()

        if not raw_message:
            return False

        normalized = normalize_text(raw_message, normalization)

        # If the message contains a real date term, it is not time-only.
        date_terms = config.get("date_direct_terms", [])

        if isinstance(date_terms, list):
            ambiguous_booking_words = {
                "معاد",
                "ميعاد",
                "موعد",
                "مواعيد",
                "المواعيد",
                "appointment",
                "slots"
            }

            for term in date_terms:
                term_text = str(term or "").strip()

                if not term_text:
                    continue

                if normalize_text(term_text, normalization) in ambiguous_booking_words:
                    continue

                normalized_term = normalize_text(term_text, normalization)

                if normalized_term and normalized_term in normalized:
                    return False

        if self.extract_explicit_date_phrase(raw_message):
            return False

        requested_time = self.extract_time(raw_message, config, normalization)

        if not requested_time:
            return False

        time_markers = [
            "الساعة",
            "الساعه",
            "ساعة",
            "ساعه",
            "الصبح",
            "صباح",
            "صباحا",
            "صباحًا",
            "الظهر",
            "ظهرا",
            "ظهرًا",
            "مساء",
            "مساءا",
            "مساءً",
            "بالليل",
            "am",
            "pm"
        ]

        if any(marker in normalized for marker in time_markers):
            return True

        # Bare numeric choices can be slot times during slot selection, but avoid
        # treating very long numbers as time.
        return bool(re.search(r"(^|\D)(\d{1,2})(?::\d{2})?(\D|$)", normalized))

    def extract_direct_date_term(
        self,
        normalized_message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> str:
        direct_terms = config.get("date_direct_terms", [])

        for term in direct_terms:
            normalized_term = normalize_text(str(term), normalization)

            if normalized_term and normalized_term in normalized_message:
                return str(term)

        return ""

    def extract_explicit_date_phrase(self, raw_message: str) -> str:
        month_names = (
            "يناير|فبراير|مارس|ابريل|أبريل|مايو|يونيو|يونيه|يوليو|يوليه|اغسطس|أغسطس|سبتمبر|اكتوبر|أكتوبر|نوفمبر|ديسمبر"
        )

        patterns = [
            rf"\b(\d{{1,2}}\s*(?:{month_names})(?:\s+\d{{4}})?)\b",
            r"\b(\d{4}-\d{1,2}-\d{1,2})\b",
            r"\b(\d{1,2}[/-]\d{1,2}(?:[/-]\d{2,4})?)\b"
        ]

        for pattern in patterns:
            match = re.search(pattern, raw_message, flags=re.IGNORECASE)

            if match:
                return match.group(1).strip()

        return ""

    def clean_date_text(self, value: str, normalization: Dict[str, Any]) -> str:
        text = str(value or "").strip()

        if not text:
            return ""

        normalized = normalize_text(text, normalization)

        direct_terms = [
            "بكرة",
            "بكره",
            "بعد بكرة",
            "بعد بكره",
            "النهارده",
            "انهارده",
            "اليوم",
            "الخميس",
            "الجمعة",
            "الجمعه",
            "السبت",
            "الأحد",
            "الاحد",
            "الاثنين",
            "الاتنين",
            "التلات",
            "الثلاثاء",
            "الأربعاء",
            "الاربعاء",
            "tomorrow",
            "today",
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday"
        ]

        for term in direct_terms:
            if normalize_text(term, normalization) in normalized:
                return term

        explicit = self.extract_explicit_date_phrase(text)

        if explicit:
            return explicit

        text = re.sub(r"^(المتاحه|المتاحة|متاح|في|على|يوم)\s+", "", text).strip()
        text = re.split(r"\s+(?:في|على|بفرع|فرع)\s+", text, maxsplit=1)[0].strip()

        return text

    def ensure_resolved_date_from_existing_state(
        self,
        variables: Dict[str, Any],
        config: Dict[str, Any],
        normalization: Dict[str, Any],
        message: str = ""
    ) -> Dict[str, Any]:
        appointment_date_path = config.get("appointment_date_path", "appointment_date")
        date_text_path = config.get("date_text_path", "date_text")

        existing_date = deep_get(variables, appointment_date_path) or deep_get(variables, "date")

        if existing_date:
            return variables

        date_text = deep_get(variables, date_text_path, "")

        if not date_text and message:
            date_text = self.extract_date_text(message, config, normalization)

        if not date_text:
            return variables

        resolved_date = self.resolve_date_text(
            date_text=str(date_text),
            message=message,
            normalization=normalization
        )

        if not resolved_date:
            return variables

        return apply_variable_patch(
            variables,
            {
                date_text_path: date_text,
                appointment_date_path: resolved_date,
                "date": resolved_date
            },
            []
        )

    def resolve_date_text(
        self,
        date_text: str,
        message: str = "",
        normalization: Optional[Dict[str, Any]] = None
    ) -> str:
        normalization = normalization or {}
        raw = normalize_digits(str(date_text or "").strip(), normalization.get("digit_map", {}))
        raw_message = normalize_digits(str(message or "").strip(), normalization.get("digit_map", {}))

        if not raw:
            return ""

        normalized = normalize_text(raw, normalization)
        normalized_message = normalize_text(raw_message, normalization) if raw_message else normalized

        today = datetime.now(TZ).date()

        relative_days = self.resolve_relative_day_offset(normalized)

        if relative_days is not None:
            return (today + timedelta(days=relative_days)).isoformat()

        weekday_index = self.resolve_weekday_index(normalized)

        if weekday_index is None and raw_message:
            weekday_index = self.resolve_weekday_index(normalized_message)

        if weekday_index is not None:
            force_next_week = self.has_next_week_marker(normalized) or self.has_next_week_marker(normalized_message)
            return self.next_weekday(today, weekday_index, force_next_week=force_next_week).isoformat()

        iso = self.parse_iso_date(raw)

        if iso:
            return iso

        numeric = self.parse_numeric_date(raw, today)

        if numeric:
            return numeric

        month_named = self.parse_named_month_date(raw, today)

        if month_named:
            return month_named

        return ""

    def resolve_relative_day_offset(self, normalized: str) -> Optional[int]:
        if any(term in normalized for term in ["بعد بكره", "بعد بكرة", "بعد غد", "بعد الغد"]):
            return 2

        if any(term in normalized for term in ["بكره", "بكرة", "غدا", "غد", "tomorrow"]):
            return 1

        if any(term in normalized for term in ["النهارده", "انهارده", "اليوم", "today"]):
            return 0

        return None

    def resolve_weekday_index(self, normalized: str) -> Optional[int]:
        weekday_map = {
            "الاثنين": 0,
            "الاتنين": 0,
            "monday": 0,
            "التلات": 1,
            "الثلاثاء": 1,
            "الثلاثا": 1,
            "tuesday": 1,
            "الاربعاء": 2,
            "الأربعاء": 2,
            "الاربع": 2,
            "wednesday": 2,
            "الخميس": 3,
            "thursday": 3,
            "الجمعه": 4,
            "الجمعة": 4,
            "friday": 4,
            "السبت": 5,
            "saturday": 5,
            "الاحد": 6,
            "الأحد": 6,
            "sunday": 6
        }

        for word, index in weekday_map.items():
            if word in normalized:
                return index

        return None

    @staticmethod
    def has_next_week_marker(normalized: str) -> bool:
        return any(term in str(normalized or "") for term in [
            "الجاي",
            "القادم",
            "اللي جاي",
            "الجاى",
            "next"
        ])

    @staticmethod
    def next_weekday(today, weekday_index: int, force_next_week: bool = False):
        days_ahead = weekday_index - today.weekday()

        if days_ahead < 0:
            days_ahead += 7

        if force_next_week and days_ahead == 0:
            days_ahead = 7

        return today + timedelta(days=days_ahead)

    def parse_iso_date(self, raw: str) -> str:
        match = re.search(r"\b(\d{4})-(\d{1,2})-(\d{1,2})\b", raw)

        if not match:
            return ""

        year = int(match.group(1))
        month = int(match.group(2))
        day = int(match.group(3))

        try:
            return datetime(year, month, day).date().isoformat()
        except ValueError:
            return ""

    def parse_numeric_date(self, raw: str, today) -> str:
        match = re.search(r"\b(\d{1,2})[/-](\d{1,2})(?:[/-](\d{2,4}))?\b", raw)

        if not match:
            return ""

        day = int(match.group(1))
        month = int(match.group(2))
        year_text = match.group(3)

        if year_text:
            year = int(year_text)
            if year < 100:
                year += 2000
        else:
            year = today.year

        try:
            candidate = datetime(year, month, day).date()
        except ValueError:
            return ""

        if not year_text and candidate < today:
            try:
                candidate = datetime(year + 1, month, day).date()
            except ValueError:
                return ""

        return candidate.isoformat()

    def parse_named_month_date(self, raw: str, today) -> str:
        normalized = raw.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا")

        month_map = {
            "يناير": 1,
            "فبراير": 2,
            "مارس": 3,
            "ابريل": 4,
            "مايو": 5,
            "يونيو": 6,
            "يونيه": 6,
            "يوليو": 7,
            "يوليه": 7,
            "اغسطس": 8,
            "سبتمبر": 9,
            "اكتوبر": 10,
            "نوفمبر": 11,
            "ديسمبر": 12
        }

        pattern = r"\b(\d{1,2})\s+([^\s\d]+)(?:\s+(\d{4}))?\b"
        match = re.search(pattern, normalized)

        if not match:
            return ""

        day = int(match.group(1))
        month_name = match.group(2)
        year_text = match.group(3)

        month = month_map.get(month_name)

        if not month:
            return ""

        year = int(year_text) if year_text else today.year

        try:
            candidate = datetime(year, month, day).date()
        except ValueError:
            return ""

        if not year_text and candidate < today:
            try:
                candidate = datetime(year + 1, month, day).date()
            except ValueError:
                return ""

        return candidate.isoformat()

    def ensure_selected_branch_from_context(
        self,
        variables: Dict[str, Any],
        assistant_config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        selected = str(deep_get(variables, "selected_branch") or "").strip()

        canonical_selected = self.resolve_canonical_branch(
            value=selected,
            assistant_config=assistant_config,
            normalization=normalization
        )

        if canonical_selected:
            if canonical_selected != selected:
                return apply_variable_patch(
                    variables,
                    {
                        "selected_branch": canonical_selected,
                        "location_branch": canonical_selected
                    },
                    []
                )
            return variables

        pending_branch = str(deep_get(variables, "booking.pending.branch") or "").strip()

        canonical_pending = self.resolve_canonical_branch(
            value=pending_branch,
            assistant_config=assistant_config,
            normalization=normalization
        )

        if canonical_pending:
            return apply_variable_patch(
                variables,
                {
                    "selected_branch": canonical_pending,
                    "location_branch": canonical_pending
                },
                []
            )

        message_branch = self.resolve_canonical_branch(
            value=message,
            assistant_config=assistant_config,
            normalization=normalization
        )

        if message_branch:
            return apply_variable_patch(
                variables,
                {
                    "selected_branch": message_branch,
                    "location_branch": message_branch
                },
                []
            )

        known_branch = self.get_known_branch(variables)

        if known_branch:
            return apply_variable_patch(
                variables,
                {
                    "selected_branch": known_branch,
                    "location_branch": known_branch
                },
                []
            )

        inferred_branch = self.infer_branch_from_available_branches(
            variables=variables,
            message=message,
            normalization=normalization
        )

        if inferred_branch:
            return apply_variable_patch(
                variables,
                {
                    "selected_branch": inferred_branch,
                    "location_branch": inferred_branch,
                    "nearest_branch": inferred_branch
                },
                []
            )

        return variables


    def get_known_branch(self, variables: Dict[str, Any]) -> str:
        for path in [
            "booking.pending.branch",
            "selected_branch",
            "location_branch",
            "nearest_branch"
        ]:
            value = str(deep_get(variables, path) or "").strip()
            if value:
                return value
        return ""



    def ensure_pending_booking_context(
        self,
        variables: Dict[str, Any],
        config: Dict[str, Any],
        assistant_config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        pending_path = config.get("pending_booking_path", "booking.pending")
        pending = deep_get(variables, pending_path, {})

        if not isinstance(pending, dict):
            pending = {}

        updates: Dict[str, Any] = {}
        patched_pending = dict(pending)

        branch = (
            patched_pending.get("branch")
            or self.get_known_branch(variables)
            or self.infer_branch_from_available_branches(
                variables=variables,
                message=message,
                normalization=normalization
            )
        )

        if branch:
            canonical_branch = self.resolve_canonical_branch(
                value=str(branch),
                assistant_config=assistant_config,
                normalization=normalization
            ) or str(branch)

            patched_pending["branch"] = canonical_branch
            updates["selected_branch"] = canonical_branch
            updates["location_branch"] = canonical_branch

            if not deep_get(variables, "nearest_branch"):
                updates["nearest_branch"] = canonical_branch

        date_value = (
            patched_pending.get("date")
            or deep_get(variables, config.get("appointment_date_path", "appointment_date"))
            or deep_get(variables, "date")
        )

        if date_value:
            patched_pending["date"] = date_value
            updates[config.get("appointment_date_path", "appointment_date")] = date_value
            updates["date"] = date_value

        date_text = (
            patched_pending.get("date_text")
            or deep_get(variables, config.get("date_text_path", "date_text"))
        )

        if date_text:
            patched_pending["date_text"] = date_text
            updates[config.get("date_text_path", "date_text")] = date_text

        time_value = patched_pending.get("time") or deep_get(variables, "appointment_time")

        if time_value:
            patched_pending["time"] = time_value
            updates["appointment_time"] = time_value

        section = patched_pending.get("section") or deep_get(variables, "service_needed")

        if section and not patched_pending.get("section"):
            patched_pending["section"] = section

        if patched_pending and patched_pending != pending:
            updates[pending_path] = patched_pending
            updates["booking.pending_summary"] = self.build_pending_summary(patched_pending)

        if not updates:
            return variables

        return apply_variable_patch(variables, updates, [])

    def infer_branch_from_available_branches(
        self,
        variables: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> str:
        branches = deep_get(variables, "available_branches", [])

        if not isinstance(branches, list) or not branches:
            return ""

        location_text = " ".join([
            str(deep_get(variables, "user_area") or ""),
            str(message or "")
        ]).strip()

        if not location_text:
            return ""

        location_norm = normalize_text(location_text, normalization)
        location_tokens = self.extract_meaningful_tokens(location_norm)

        if not location_tokens:
            return ""

        best_branch = ""
        best_score = 0

        for branch_item in branches:
            if not isinstance(branch_item, dict):
                continue

            branch_name = str(branch_item.get("branch") or "").strip()
            branch_area = str(branch_item.get("area") or "").strip()

            if not branch_name or not branch_area:
                continue

            area_norm = normalize_text(branch_area, normalization)
            score = 0

            for token in location_tokens:
                if token and token in area_norm:
                    score += 1

            if score > best_score:
                best_score = score
                best_branch = branch_name

        if best_score > 0:
            return best_branch

        return ""

    @staticmethod
    def extract_meaningful_tokens(text: str) -> List[str]:
        raw_tokens = re.findall(r"[\w\u0600-\u06FF]+", str(text or "").lower())

        stopwords = {
            "انا",
            "أنا",
            "ساكن",
            "في",
            "قولي",
            "قوللي",
            "قولى",
            "اقرب",
            "أقرب",
            "فرع",
            "ليا",
            "لي",
            "وايه",
            "ايه",
            "إيه",
            "المواعيد",
            "المتاحه",
            "المتاحة",
            "يوم",
            "الجاي",
            "القادم",
            "عايز",
            "عاوز",
            "ممكن",
            "لو",
            "تحب",
            "ده",
            "هذا",
            "اللي",
            "اكد",
            "أكد",
            "المعاد",
            "موعد",
            "ميعاد",
            "الساعة",
            "الساعه"
        }

        output = []

        for token in raw_tokens:
            token = token.strip()

            if not token:
                continue

            if token in stopwords:
                continue

            if len(token) < 3:
                continue

            output.append(token)

        return output[:12]
    def resolve_canonical_branch(
        self,
        value: str,
        assistant_config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> str:
        text = str(value or "").strip()

        if not text:
            return ""

        aliases = assistant_config.get("branch_aliases", {})

        if not isinstance(aliases, dict):
            return ""

        normalized_text = normalize_text(text, normalization)

        for canonical, alias_list in aliases.items():
            canonical_text = str(canonical or "").strip()

            if not canonical_text:
                continue

            candidates = [canonical_text]

            if isinstance(alias_list, list):
                candidates.extend([str(item or "") for item in alias_list])

            for candidate in candidates:
                normalized_candidate = normalize_text(candidate, normalization)

                if not normalized_candidate:
                    continue

                if normalized_candidate == normalized_text:
                    return canonical_text

                if normalized_candidate in normalized_text:
                    return canonical_text

        return ""

    def is_booking_or_availability_request(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        normalization = context.assistant_config.get("normalization", {})
        phrases = config.get("trigger_phrases", [])

        if matches_any(context.user_message, phrases, normalization):
            return True

        date_text = self.extract_date_text(context.user_message, config, normalization)

        if date_text and self.get_known_branch(variables):
            return True

        stage_path = config.get("stage_path", "booking.stage")
        stage = deep_get(variables, stage_path, "")

        return stage in config.get("active_request_stages", [])

    def is_new_availability_request(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        normalization = context.assistant_config.get("normalization", {})
        message = normalize_text(context.user_message, normalization)

        availability_terms = config.get("availability_request_terms", [])

        if not isinstance(availability_terms, list):
            availability_terms = []

        has_availability_intent = any(
            normalize_text(term, normalization) in message
            for term in availability_terms
            if str(term or "").strip()
        )

        date_text = self.extract_date_text(context.user_message, config, normalization)

        if not has_availability_intent and not date_text:
            return False

        branch = self.get_known_branch(variables)
        appointment_date = (
            deep_get(variables, config.get("appointment_date_path", "appointment_date"))
            or deep_get(variables, "date")
        )

        return bool(branch and (appointment_date or date_text))

    def get_missing_required_create_fields(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> List[str]:
        missing = get_missing_paths(
            config.get("required_before_create", []),
            variables
        )

        return [path for path in missing if not self.is_ignorable_create_missing(path, variables)]

    def is_ignorable_create_missing(self, path: str, variables: Dict[str, Any]) -> bool:
        if path == "variables.customer_profile.phone":
            return bool(
                deep_get(variables, "customer_profile.phone")
                or deep_get(variables, "phone")
                or deep_get(variables, "customer_phone")
            )

        if path == "variables.booking.pending.branch":
            return bool(self.get_known_branch(variables))

        if path == "variables.booking.pending.date":
            return bool(
                deep_get(variables, "booking.pending.date")
                or deep_get(variables, "appointment_date")
                or deep_get(variables, "date")
            )

        if path == "variables.booking.pending.date_text":
            return bool(
                deep_get(variables, "booking.pending.date_text")
                or deep_get(variables, "date_text")
            )

        if path == "variables.booking.pending.time":
            return bool(
                deep_get(variables, "booking.pending.time")
                or deep_get(variables, "appointment_time")
            )

        return False


    def render_missing_question(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        missing: List[str],
        message: str
    ) -> str:
        templates = config.get("templates", {})
        missing_set = set(missing)

        template_key = "missing_fields"

        if missing_set in [{"variables.date_text"}, {"variables.appointment_date"}]:
            template_key = "missing_date"
        elif missing_set == {"variables.selected_branch"}:
            template_key = "missing_branch"
        elif missing_set == {"variables.customer_profile.full_name"}:
            template_key = "missing_full_name"
        elif missing_set == {"variables.customer_profile.phone"}:
            template_key = "missing_phone"
        elif missing_set == {"variables.customer_profile.plate_number"}:
            template_key = "missing_plate_number"
        elif missing_set == {
            "variables.customer_profile.full_name",
            "variables.customer_profile.plate_number"
        }:
            template_key = "missing_name_and_plate"
        elif missing_set == {
            "variables.customer_profile.full_name",
            "variables.customer_profile.phone"
        }:
            template_key = "missing_name_and_phone"
        elif missing_set == {
            "variables.customer_profile.phone",
            "variables.customer_profile.plate_number"
        }:
            template_key = "missing_phone_and_plate"
        elif missing_set == {
            "variables.customer_profile.full_name",
            "variables.customer_profile.phone",
            "variables.customer_profile.plate_number"
        }:
            template_key = "missing_name_phone_and_plate"

        labels = config.get("field_labels", {})
        missing_text = format_missing_fields(missing, labels)

        return render_template(
            templates.get(template_key, templates.get("missing_fields", "BOOKING_MISSING_FIELDS")),
            {
                "variables": variables,
                "missing_fields": missing_text,
                "missing_paths": missing,
                "message": message
            }
        )

    def extract_customer_details(
        self,
        message: str,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        extracted = extract_by_patterns(
            message=message,
            patterns=config.get("extraction_patterns", []),
            variables=variables,
            normalization_config=normalization
        )

        if not isinstance(extracted, dict):
            extracted = {}

        if self.is_control_only_message(message, normalization):
            extracted.pop("customer_profile.full_name", None)

        fallback = self.extract_customer_details_fallback(
            message=message,
            variables=variables,
            normalization=normalization
        )

        for key, value in fallback.items():
            if key not in extracted or extracted.get(key) in [None, "", [], {}]:
                extracted[key] = value

        if "customer_profile.full_name" in extracted:
            full_name = str(extracted.get("customer_profile.full_name") or "").strip()

            if (
                self.is_control_only_message(message, normalization)
                or not self.message_has_name_signal(message, normalization)
                or not self.looks_like_person_name(full_name)
            ):
                extracted.pop("customer_profile.full_name", None)

        if not extracted:
            return {}

        return self.post_process_extracted_fields(extracted, normalization)

    def extract_customer_details_fallback(
        self,
        message: str,
        variables: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        output: Dict[str, Any] = {}
        text = str(message or "").strip()
        normalized = normalize_text(text, normalization)

        if not deep_get(variables, "customer_profile.phone"):
            phone_match = re.search(r"(01\d{9}|\+?20\d{10,11})", normalize_digits(text, normalization.get("digit_map", {})))
            if phone_match:
                output["customer_profile.phone"] = phone_match.group(1).strip()

        if (
            not deep_get(variables, "customer_profile.full_name")
            and self.message_has_name_signal(text, normalization)
            and not self.is_control_only_message(text, normalization)
        ):
            name_match = re.search(
                r"(?:اسمي|انا اسمي|الإسم|الاسم|name is|my name is)\s+([^،,.!?؟\n]+)",
                text,
                flags=re.IGNORECASE
            )

            if name_match:
                name = self.clean_name(name_match.group(1))
                if self.looks_like_person_name(name):
                    output["customer_profile.full_name"] = name

        if not deep_get(variables, "customer_profile.plate_number"):
            plate = self.extract_plate_fallback(text, normalization)

            if plate:
                output["customer_profile.plate_number"] = plate

        if not output:
            return output

        # If a message starts with "اسمي", never let the generic plate/name patterns overwrite the name.
        if "اسمي" in normalized or "انا اسمي" in normalized:
            if output.get("customer_profile.full_name"):
                output.pop("customer_profile.plate_number", None)

        return output

    def ensure_valid_customer_profile(
        self,
        variables: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        full_name = str(deep_get(variables, "customer_profile.full_name") or "").strip()

        if not full_name:
            return variables

        if self.looks_like_person_name(full_name):
            return variables

        return apply_variable_patch(
            variables,
            {},
            ["customer_profile.full_name"]
        )

    def has_customer_detail_signal(self, message: str, normalization: Dict[str, Any]) -> bool:
        text = str(message or "").strip()
        normalized = normalize_text(text, normalization)

        detail_markers = [
            "اسمي",
            "انا اسمي",
            "الاسم",
            "الإسم",
            "تليفون",
            "تلفون",
            "موبايل",
            "رقم العربية",
            "نمر العربية",
            "نمرة العربية",
            "رقم اللوحه",
            "رقم اللوحة",
            "اللوحه",
            "اللوحة",
            "لوحتي",
            "لوحتى",
            "plate",
            "phone",
            "mobile",
            "name is",
            "my name is"
        ]

        if any(normalize_text(marker, normalization) in normalized for marker in detail_markers):
            return True

        if re.search(r"(01\d{9}|\+?20\d{10,11})", normalize_digits(text, normalization.get("digit_map", {}))):
            return True

        # A standalone plate-like reply during customer-detail collection is a detail.
        if self.extract_plate_fallback(text, normalization):
            return True

        return False

    def message_has_name_signal(self, message: str, normalization: Dict[str, Any]) -> bool:
        normalized = normalize_text(str(message or ""), normalization)

        name_markers = [
            "اسمي",
            "انا اسمي",
            "الاسم",
            "الإسم",
            "name is",
            "my name is"
        ]

        return any(normalize_text(marker, normalization) in normalized for marker in name_markers)

    def is_control_only_message(self, message: str, normalization: Dict[str, Any]) -> bool:
        normalized = normalize_text(str(message or ""), normalization)
        normalized = re.sub(r"\s+", " ", normalized).strip()

        if not normalized:
            return False

        control_terms = {
            "اه",
            "اها",
            "ايوه",
            "ايوا",
            "نعم",
            "تمام",
            "اوكي",
            "اوك",
            "اكيد",
            "اكد",
            "اكده",
            "اكدها",
            "اكد الحجز",
            "اكد المعاد",
            "اكد الموعد",
            "confirm",
            "confirmed",
            "yes",
            "ok",
            "okay"
        }

        tokens = [token for token in re.findall(r"[\w\u0600-\u06FF]+", normalized) if token]

        if not tokens:
            return False

        if all(token in control_terms for token in tokens):
            return True

        # Mixed short confirmation/control phrases like "اه اكده تمام" should
        # never be accepted as a full name.
        if len(tokens) <= 5 and any(token in control_terms for token in tokens):
            customer_markers = [
                "اسمي",
                "الاسم",
                "رقم",
                "العربيه",
                "العربية",
                "اللوحه",
                "اللوحة",
                "تليفون",
                "تلفون",
                "موبايل"
            ]

            if not any(marker in normalized for marker in customer_markers):
                return True

        return False

    def clean_name(self, value: str) -> str:
        text = str(value or "").strip()
        text = re.sub(r"\s+", " ", text)
        text = re.sub(
            r"\s+(?:ورقم|و رقم|وتليفوني|و تليفوني|وتلفوني|و تلفوني|وموبايل|و موبايل|ولوحتي|و لوحتي|واللوحة|و اللوحة).*$",
            "",
            text
        ).strip()
        return text

    def looks_like_person_name(self, value: str) -> bool:
        text = str(value or "").strip()

        if not text:
            return False

        if re.search(r"\d", text):
            return False

        blocked = [
            "العربية",
            "العربيه",
            "اللوحة",
            "اللوحه",
            "رقم",
            "موبايل",
            "تليفون",
            "تلفون",
            "فرع",
            "ميعاد",
            "معاد",
            "موعد",
            "الحجز",
            "تمام",
            "اكد",
            "أكد",
            "اكده",
            "أكده",
            "اكدها",
            "أكدها",
            "ايوه",
            "أيوه",
            "اه",
            "أه",
            "اوكي",
            "أوكي",
            "confirm",
            "confirmed",
            "yes",
            "ok",
            "okay"
        ]

        normalized = text.replace("ة", "ه").replace("ى", "ي").replace("أ", "ا").replace("إ", "ا").replace("آ", "ا")

        if any(word.replace("ة", "ه").replace("ى", "ي").replace("أ", "ا").replace("إ", "ا").replace("آ", "ا") in normalized for word in blocked):
            return False

        parts = [part for part in text.split() if part.strip()]

        if len(parts) < 2:
            return False

        return 2 <= len(parts) <= 6 and all(len(part) >= 2 for part in parts)

    def extract_plate_fallback(self, text: str, normalization: Dict[str, Any]) -> str:
        digit_map = normalization.get("digit_map", {})
        normalized_digits = normalize_digits(str(text or ""), digit_map)

        labelled = re.search(
            r"(?:رقم العربية|نمر العربية|نمرة العربية|رقم اللوحه|رقم اللوحة|اللوحه|اللوحة|لوحتي|لوحتى|plate)\D*([^\n،,.!?؟]{2,30})",
            normalized_digits,
            flags=re.IGNORECASE
        )

        if labelled:
            candidate = labelled.group(1).strip()
            candidate = self.normalize_plate_number(candidate, normalization)
            if self.looks_like_plate_number(candidate):
                return candidate

        standalone = self.normalize_plate_number(normalized_digits, normalization)

        if self.looks_like_plate_number(standalone):
            return standalone

        return ""

    def looks_like_plate_number(self, value: str) -> bool:
        text = str(value or "").strip()

        if not text:
            return False

        has_digit = bool(re.search(r"\d", text))
        has_letter = bool(re.search(r"[A-Za-z\u0600-\u06FF]", text))

        if not has_digit:
            return False

        if len(text) < 2 or len(text) > 30:
            return False

        blocked = [
            "اسمي",
            "الاسم",
            "الإسم",
            "موبايل",
            "تليفون",
            "تلفون",
            "موعد",
            "ميعاد",
            "معاد",
            "فرع"
        ]

        normalized = text.replace("ة", "ه").replace("ى", "ي")

        if any(word in normalized for word in blocked):
            return False

        return has_digit or has_letter

    def build_pending_summary(self, pending: Dict[str, Any]) -> str:
        if not isinstance(pending, dict):
            return ""

        parts = []

        branch = str(pending.get("branch") or "").strip()
        date = str(pending.get("date_text") or pending.get("date") or "").strip()
        time = str(pending.get("time") or "").strip()
        section = str(pending.get("section") or "").strip()

        if branch:
            parts.append(f"branch={branch}")

        if date:
            parts.append(f"date={date}")

        if time:
            parts.append(f"time={time}")

        if section:
            parts.append(f"section={section}")

        return " | ".join(parts)

    def filter_slots_by_service_needed(
        self,
        tool_result: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> Dict[str, Any]:
        if not isinstance(tool_result, dict):
            return tool_result

        service_needed = str(deep_get(variables, "service_needed") or "").strip()

        if not service_needed:
            return tool_result

        slots = tool_result.get("available_slots")

        if not isinstance(slots, list):
            return tool_result

        service_norm = self.norm_section(service_needed)

        filtered = [
            slot for slot in slots
            if isinstance(slot, dict)
            and self.norm_section(str(slot.get("section") or "")) == service_norm
        ]

        patched = dict(tool_result)
        patched["available_slots"] = filtered
        patched["slots_found"] = len(filtered) > 0

        if filtered:
            patched["available_slots_text"] = self.render_slots_text(filtered)
        else:
            patched["available_slots_text"] = ""

        return patched

    def render_slots_text(self, slots: List[Dict[str, Any]]) -> str:
        lines = []

        for index, slot in enumerate(slots, 1):
            time = str(slot.get("time") or "").strip()
            section = str(slot.get("section") or "").strip()
            remaining = (
                slot.get("remaining_capacity")
                if slot.get("remaining_capacity") is not None
                else slot.get("places_left")
            )

            parts = [f"{index})"]

            if time:
                parts.append(time)

            if section:
                parts.append(section)

            if remaining is not None and str(remaining).strip() != "":
                parts.append(f"remaining={remaining}")

            lines.append(" - ".join(parts))

        return "\n".join(lines)

    def is_booking_completed(self, variables: Dict[str, Any]) -> bool:
        status = str(deep_get(variables, "booking_status") or "").lower()
        stage = str(deep_get(variables, "booking.stage") or "").lower()
        visit_id = deep_get(variables, "visit_id")

        return bool(
            visit_id
            or status in {"confirmed", "booking_confirmed", "booked"}
            or stage in {"confirmed", "booking_confirmed", "booked"}
        )

    def is_polite_closing(
        self,
        message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        terms = config.get("closing_phrases", [
            "شكرا",
            "شكرًا",
            "متشكر",
            "تمام شكرا",
            "تمام شكرًا",
            "تسلم",
            "thanks",
            "thank you"
        ])

        return matches_any(message, terms, normalization)

    def looks_like_duplicate_confirmation(
        self,
        message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        duplicate_terms = config.get("duplicate_confirmation_phrases", [])
        confirmation_terms = config.get("confirmation_phrases", [])

        return (
            matches_any(message, duplicate_terms, normalization)
            or matches_any(message, confirmation_terms, normalization)
        )

    def post_process_extracted_fields(
        self,
        extracted: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        output = dict(extracted)

        plate = output.get("customer_profile.plate_number")

        if plate:
            plate_text = self.normalize_plate_number(
                str(plate),
                normalization
            )

            if self.looks_like_plate_number(plate_text):
                output["customer_profile.plate_number"] = plate_text
            else:
                output.pop("customer_profile.plate_number", None)

        full_name = output.get("customer_profile.full_name")

        if full_name:
            clean = self.clean_name(str(full_name))

            if self.looks_like_person_name(clean):
                output["customer_profile.full_name"] = re.sub(
                    r"\s+",
                    " ",
                    clean.strip()
                )
            else:
                output.pop("customer_profile.full_name", None)

        phone = output.get("customer_profile.phone")

        if phone:
            output["customer_profile.phone"] = normalize_digits(
                str(phone).strip(),
                normalization.get("digit_map", {})
            )

        return output

    @staticmethod
    def norm_section(value: str) -> str:
        return re.sub(r"\s+", " ", str(value or "").strip().lower())

    @staticmethod
    def normalize_plate_number(value: str, normalization: Dict[str, Any]) -> str:
        digit_map = normalization.get("digit_map", {})
        text = str(value or "")

        for src, dst in digit_map.items():
            text = text.replace(src, dst)

        text = re.sub(r"[،,.!?؟:;]+", " ", text)
        text = re.sub(r"\s+", " ", text).strip()

        return text
