from typing import Any, Dict, List

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_variable_patch,
    build_object_from_mapping,
    deep_get,
    get_subagent_config,
    matches_any,
    render_template
)


class HandoffSubagent:
    """
    Handoff executor for the LangGraph architecture.

    Responsibilities:
    - detect configured handoff intent
    - apply configured handoff variable updates and clears
    - return an internal answer label/draft signal

    Architecture boundaries:
    - This executor is deterministic and config-driven.
    - It does not own final customer-facing wording.
    - It must not contain domain/customer phrase hardcoding.
    - Final wording is generated by graph.response_node and validated by quality_guard.
    """

    name = "handoff"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not self.is_enabled(config):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {}) or {}

        matched_rule = self.find_matching_rule(
            message=context.user_message,
            config=config,
            variables=variables,
            normalization=normalization
        )

        if not matched_rule:
            return SubagentResult(handled=False)

        updates = self.build_updates(
            config=config,
            rule=matched_rule,
            variables=variables,
            message=context.user_message
        )

        clear = self.build_clear_list(config=config, rule=matched_rule)

        patched_variables = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=clear
        )

        answer = render_template(
            self.get_answer_template(config=config, rule=matched_rule),
            {
                "variables": patched_variables,
                "rule": matched_rule,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action=self.get_action(config=config, rule=matched_rule),
            answer=answer,
            variable_updates=patched_variables,
            clear_variables=[],
            selected_subagent=self.name,
            notes=self.build_note(config=config, event="triggered", rule=matched_rule)
        )

    def is_enabled(self, config: Dict[str, Any]) -> bool:
        return bool(config.get("enabled", False))

    def find_matching_rule(
        self,
        message: str,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        rules = self.get_rules(config)

        if rules:
            for rule in rules:
                if not self.rule_enabled(rule):
                    continue

                if not self.rule_matches_message(
                    message=message,
                    rule=rule,
                    normalization=normalization
                ):
                    continue

                if not self.rule_matches_variable_conditions(
                    rule=rule,
                    variables=variables
                ):
                    continue

                return rule

            return {}

        # Backward-compatible config path:
        # Older bundles may define trigger_phrases directly on the handoff config.
        # The actual phrases still live in config, not Python.
        trigger_phrases = config.get("trigger_phrases", [])

        if matches_any(message, trigger_phrases if isinstance(trigger_phrases, list) else [], normalization):
            return {
                "id": config.get("default_rule_id", self.name),
                "trigger_phrases": trigger_phrases,
                "variable_updates": config.get("variable_updates", {}),
                "clear_variables": config.get("clear_variables", []),
                "answer_template": config.get("answer_template", ""),
                "action": config.get("action", config.get("default_action", self.name))
            }

        return {}

    def get_rules(self, config: Dict[str, Any]) -> List[Dict[str, Any]]:
        rules = config.get("rules", [])

        if not isinstance(rules, list):
            return []

        return [rule for rule in rules if isinstance(rule, dict)]

    def rule_enabled(self, rule: Dict[str, Any]) -> bool:
        return bool(rule.get("enabled", True))

    def rule_matches_message(
        self,
        message: str,
        rule: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        phrases = rule.get("phrases", rule.get("trigger_phrases", []))

        if isinstance(phrases, list) and phrases:
            if matches_any(message, phrases, normalization):
                return True

        any_phrases = rule.get("any_phrases", [])

        if isinstance(any_phrases, list) and any_phrases:
            if matches_any(message, any_phrases, normalization):
                return True

        all_required_phrases = rule.get("all_required_phrases", [])

        if isinstance(all_required_phrases, list) and all_required_phrases:
            return all(
                matches_any(message, [phrase], normalization)
                for phrase in all_required_phrases
                if str(phrase or "").strip()
            )

        return bool(rule.get("allow_without_phrase_match", False))

    def rule_matches_variable_conditions(
        self,
        rule: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        conditions = rule.get("variable_conditions", [])

        if not isinstance(conditions, list):
            return True

        for condition in conditions:
            if not isinstance(condition, dict):
                continue

            path = str(condition.get("path") or "").strip()

            if not path:
                continue

            current = deep_get(variables, path)

            if condition.get("exists") is True and current in [None, "", [], {}]:
                return False

            if condition.get("exists") is False and current not in [None, "", [], {}]:
                return False

            if "equals" in condition and current != condition.get("equals"):
                return False

            if "not_equals" in condition and current == condition.get("not_equals"):
                return False

            allowed_values = condition.get("in")
            if isinstance(allowed_values, list) and current not in allowed_values:
                return False

            disallowed_values = condition.get("not_in")
            if isinstance(disallowed_values, list) and current in disallowed_values:
                return False

        return True

    def build_updates(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        variables: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        updates: Dict[str, Any] = {}

        config_updates = config.get("variable_updates", {})
        if isinstance(config_updates, dict):
            updates.update(config_updates)

        rule_updates = rule.get("variable_updates", {})
        if isinstance(rule_updates, dict):
            updates.update(rule_updates)

        update_mappings = rule.get("update_mappings", config.get("update_mappings", {}))

        if isinstance(update_mappings, dict) and update_mappings:
            mapped = build_object_from_mapping(update_mappings, {
                "variables": variables,
                "rule": rule,
                "message": message
            })

            if isinstance(mapped, dict):
                updates.update(mapped)

        return updates

    def build_clear_list(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any]
    ) -> List[str]:
        clear: List[str] = []

        config_clear = config.get("clear_variables", [])
        if isinstance(config_clear, list):
            clear.extend([str(item) for item in config_clear if str(item or "").strip()])

        rule_clear = rule.get("clear_variables", [])
        if isinstance(rule_clear, list):
            clear.extend([str(item) for item in rule_clear if str(item or "").strip()])

        output: List[str] = []
        for item in clear:
            if item not in output:
                output.append(item)

        return output

    def get_answer_template(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any]
    ) -> str:
        template = str(
            rule.get("answer_template")
            or rule.get("template")
            or config.get("answer_template")
            or ""
        ).strip()

        if template:
            return template

        templates = config.get("templates", {})
        if isinstance(templates, dict):
            default_template_key = str(
                rule.get("template_key")
                or config.get("default_template_key")
                or "default"
            ).strip()

            template_from_map = str(templates.get(default_template_key) or "").strip()
            if template_from_map:
                return template_from_map

        fallback_prefix = str(config.get("template_fallback_prefix") or self.name).strip().upper()
        fallback_suffix = str(config.get("template_fallback_suffix") or "triggered").strip().upper()

        return f"{fallback_prefix}_{fallback_suffix}"

    def get_action(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any]
    ) -> str:
        return str(
            rule.get("action")
            or config.get("action")
            or config.get("default_action")
            or self.name
        ).strip()

    def build_note(
        self,
        config: Dict[str, Any],
        event: str,
        rule: Dict[str, Any]
    ) -> str:
        notes_config = config.get("notes", {})

        if isinstance(notes_config, dict):
            template = str(notes_config.get(event) or "").strip()

            if template:
                return template.format(
                    rule_id=rule.get("id", ""),
                    subagent=self.name,
                    event=event
                )

        return f"{self.name}:{event}:{rule.get('id', '')}"
