import re
from typing import Any, Dict, List, Optional

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_tool_update_rules,
    apply_variable_patch,
    compact_dict,
    deep_get,
    get_subagent_config,
    matches_any,
    render_template
)


class LocationSubagent:
    """
    Config-driven location executor for the LangGraph architecture.

    Responsibilities:
    - detect/extract user location text from configured patterns/markers
    - use already-provided coordinates from configured variable paths
    - ask for location only when configured nearest-branch intent is active and no location exists
    - call the configured nearest-location/branch operation
    - update source-of-truth location/branch variables from tool results

    Not responsible for final customer-facing wording.
    Final wording is generated by graph.response_node and validated by quality_guard.

    Architecture rule:
    - No domain/customer-facing phrase hardcoding in Python.
    - Phrases, templates, result paths, coordinate paths, and active-flow values live in domain_bundle.json.
    """

    name = "location"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {})
        observations: List[Dict[str, Any]] = []

        location = self.extract_location(
            message=context.user_message,
            config=config,
            normalization=normalization
        )

        coordinates = self.extract_coordinates(
            variables=variables,
            config=config
        )

        nearest_requested = matches_any(
            context.user_message,
            self.config_list(config, "nearest_branch_request_phrases"),
            normalization
        )

        if not location and not coordinates:
            if nearest_requested or self.location_flow_active(variables, config):
                patched_variables = self.apply_configured_updates(
                    variables=variables,
                    config=config,
                    key="on_nearest_branch_request_updates"
                )

                answer = render_template(
                    self.template_label(config, "ask_location_for_nearest_branch"),
                    {
                        "variables": patched_variables,
                        "message": context.user_message
                    }
                )

                return SubagentResult(
                    handled=True,
                    action="ask_user",
                    answer=answer,
                    variable_updates=patched_variables,
                    observations=observations,
                    selected_subagent=self.name,
                    tool_calls_used=0,
                    notes="location required before configured lookup"
                )

            return SubagentResult(handled=False)

        tool_name = str(config.get("tool_name", "") or "").strip()
        operation = str(config.get("operation", "") or "").strip()

        if not tool_name or not operation:
            return SubagentResult(
                handled=True,
                action="reply",
                answer=render_template(
                    self.template_label(config, "tool_error"),
                    {
                        "variables": variables,
                        "message": context.user_message
                    }
                ),
                variable_updates=variables,
                observations=observations,
                selected_subagent=self.name,
                tool_calls_used=0,
                notes="location tool configuration missing"
            )

        arguments = self.build_tool_arguments(
            config=config,
            location=location,
            coordinates=coordinates
        )

        try:
            tool_result = context.tool_runner.call(
                tool_name=tool_name,
                operation=operation,
                arguments=compact_dict(arguments)
            )
        except Exception as exc:
            tool_result = {
                "ok": False,
                "error": f"{type(exc).__name__}: {exc}",
            }

        observations.append({
            "subagent": self.name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        manual_updates = self.build_manual_updates(
            config=config,
            variables=updated_variables,
            location=location,
            coordinates=coordinates,
            tool_result=tool_result
        )

        updated_variables = apply_variable_patch(
            variables=updated_variables,
            updates=manual_updates,
            clear=[]
        )

        answer = render_template(
            self.result_label(config, tool_result),
            {
                "variables": updated_variables,
                "result": tool_result,
                "arguments": arguments,
                "location": location,
                "coordinates": coordinates,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="reply",
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=1,
            notes="location tool executed"
        )

    def build_tool_arguments(
        self,
        config: Dict[str, Any],
        location: str,
        coordinates: Dict[str, Any]
    ) -> Dict[str, Any]:
        arguments: Dict[str, Any] = {}

        if location:
            location_argument = str(config.get("location_argument", "location") or "").strip()
            if location_argument:
                arguments[location_argument] = location

        if coordinates:
            coordinate_argument_names = config.get("coordinate_argument_names", {})
            if not isinstance(coordinate_argument_names, dict):
                coordinate_argument_names = {}

            lat_arg = str(coordinate_argument_names.get("latitude", "latitude") or "").strip()
            lng_arg = str(coordinate_argument_names.get("longitude", "longitude") or "").strip()

            if lat_arg:
                arguments[lat_arg] = coordinates.get("latitude")

            if lng_arg:
                arguments[lng_arg] = coordinates.get("longitude")

        return arguments

    def build_manual_updates(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        location: str,
        coordinates: Dict[str, Any],
        tool_result: Dict[str, Any]
    ) -> Dict[str, Any]:
        updates: Dict[str, Any] = {}

        if not isinstance(tool_result, dict):
            return updates

        if self.result_ok(config=config, tool_result=tool_result):
            user_area = self.first_present_from_result(
                tool_result=tool_result,
                paths=self.config_list(config, "result_user_area_paths")
            )

            if not user_area:
                user_area = location or deep_get(variables, config.get("user_area_path", "user_area"))

            if user_area:
                updates[str(config.get("user_area_path", "user_area") or "user_area")] = self.cleanup_location(
                    user_area,
                    config
                )

            coordinate_update_paths = config.get("coordinate_update_paths", {})
            if not isinstance(coordinate_update_paths, dict):
                coordinate_update_paths = {}

            if coordinates:
                lat_path = str(coordinate_update_paths.get("latitude", "user_coordinates.latitude") or "").strip()
                lng_path = str(coordinate_update_paths.get("longitude", "user_coordinates.longitude") or "").strip()

                if lat_path:
                    updates[lat_path] = coordinates.get("latitude")

                if lng_path:
                    updates[lng_path] = coordinates.get("longitude")

        if self.branch_found(config=config, tool_result=tool_result):
            branch = self.first_present_from_result(
                tool_result=tool_result,
                paths=self.config_list(config, "result_branch_paths")
            )

            if branch:
                nearest_path = str(config.get("nearest_branch_path", "nearest_branch") or "").strip()
                location_branch_path = str(config.get("location_branch_path", "location_branch") or "").strip()
                selected_branch_path = str(config.get("selected_branch_path", "selected_branch") or "").strip()

                if nearest_path:
                    updates[nearest_path] = branch

                if location_branch_path:
                    updates[location_branch_path] = branch

                if config.get("set_selected_branch_on_match", True) and selected_branch_path:
                    updates[selected_branch_path] = branch

        extra_update_mappings = config.get("manual_update_mappings", {})
        if isinstance(extra_update_mappings, dict):
            for target_path, result_path in extra_update_mappings.items():
                target = str(target_path or "").strip()
                source = str(result_path or "").strip()

                if not target or not source:
                    continue

                value = deep_get(tool_result, source)
                if value not in [None, "", [], {}]:
                    updates[target] = value

        return updates

    def result_label(self, config: Dict[str, Any], tool_result: Dict[str, Any]) -> str:
        if not isinstance(tool_result, dict):
            return self.template_label(config, "tool_error")

        if not self.result_ok(config=config, tool_result=tool_result):
            return self.template_label(config, "tool_error")

        if self.branch_found(config=config, tool_result=tool_result):
            return self.template_label(config, "branch_found")

        return self.template_label(config, "branch_not_found")

    def result_ok(self, config: Dict[str, Any], tool_result: Dict[str, Any]) -> bool:
        result_detection = config.get("result_detection", {})
        if not isinstance(result_detection, dict):
            result_detection = {}

        ok_path = str(result_detection.get("ok_path", "ok") or "").strip()
        ok_value = result_detection.get("ok_value", True)

        if not ok_path:
            return True

        value = deep_get(tool_result, ok_path)
        return value == ok_value

    def branch_found(self, config: Dict[str, Any], tool_result: Dict[str, Any]) -> bool:
        result_detection = config.get("result_detection", {})
        if not isinstance(result_detection, dict):
            result_detection = {}

        branch_found_path = str(result_detection.get("branch_found_path", "branch_found") or "").strip()
        branch_found_value = result_detection.get("branch_found_value", True)

        if branch_found_path:
            value = deep_get(tool_result, branch_found_path)
            if value == branch_found_value:
                return True
            if value not in [None, ""]:
                return False

        branch = self.first_present_from_result(
            tool_result=tool_result,
            paths=self.config_list(config, "result_branch_paths")
        )

        return bool(branch)

    def extract_location(
        self,
        message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> str:
        raw_message = str(message or "").strip()

        if not raw_message:
            return ""

        patterns = self.config_list(config, "location_patterns")

        for item in patterns:
            if not isinstance(item, dict):
                continue

            regex = str(item.get("regex", "") or "")
            group = self.safe_int(item.get("group", 1), 1)

            if not regex:
                continue

            try:
                match = re.search(regex, raw_message, flags=re.IGNORECASE)
            except re.error:
                continue

            if match:
                try:
                    value = match.group(group).strip()
                except Exception:
                    value = match.group(0).strip()

                value = self.cleanup_location(value, config)
                if value:
                    return value

        trigger_phrases = self.config_list(config, "location_trigger_phrases")

        if matches_any(raw_message, trigger_phrases, normalization):
            cleaned = raw_message

            for phrase in trigger_phrases:
                phrase_text = str(phrase or "").strip()
                if not phrase_text:
                    continue

                cleaned = re.sub(
                    re.escape(phrase_text),
                    " ",
                    cleaned,
                    flags=re.IGNORECASE
                )

            cleaned = self.cleanup_location(cleaned, config)

            if cleaned:
                return cleaned

        return ""

    def extract_coordinates(
        self,
        variables: Dict[str, Any],
        config: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        config = config or {}

        coordinate_paths = config.get("coordinate_paths", {})
        if not isinstance(coordinate_paths, dict):
            coordinate_paths = {}

        latitude_paths = coordinate_paths.get("latitude", [])
        longitude_paths = coordinate_paths.get("longitude", [])

        if not isinstance(latitude_paths, list) or not latitude_paths:
            latitude_paths = [
                "latitude",
                "lat",
                "location.latitude",
                "user_location.latitude",
                "user_coordinates.latitude"
            ]

        if not isinstance(longitude_paths, list) or not longitude_paths:
            longitude_paths = [
                "longitude",
                "lng",
                "lon",
                "location.longitude",
                "user_location.longitude",
                "user_coordinates.longitude"
            ]

        raw_lat = self.first_present_from_variables(variables, latitude_paths)
        raw_lng = self.first_present_from_variables(variables, longitude_paths)

        if raw_lat in [None, ""] or raw_lng in [None, ""]:
            return {}

        try:
            lat = float(raw_lat)
            lng = float(raw_lng)
        except Exception:
            return {}

        bounds = config.get("coordinate_bounds", {})
        if not isinstance(bounds, dict):
            bounds = {}

        min_lat = float(bounds.get("min_latitude", -90))
        max_lat = float(bounds.get("max_latitude", 90))
        min_lng = float(bounds.get("min_longitude", -180))
        max_lng = float(bounds.get("max_longitude", 180))

        if lat < min_lat or lat > max_lat or lng < min_lng or lng > max_lng:
            return {}

        return {
            "latitude": lat,
            "longitude": lng
        }

    def location_flow_active(self, variables: Dict[str, Any], config: Dict[str, Any]) -> bool:
        intent_path = str(config.get("location_intent_path", "location.intent") or "").strip()
        intent = str(deep_get(variables, intent_path, "") or "").strip()

        if not intent:
            return False

        active_values = self.config_list(config, "active_intent_values")

        if not active_values:
            active_values = self.config_list(config, "location_flow_active_values")

        if not active_values:
            active_values = [str(config.get("default_intent_value", "") or "").strip()]

        active_values = [str(item or "").strip() for item in active_values if str(item or "").strip()]

        return bool(active_values and intent in active_values)

    @staticmethod
    def cleanup_location(location: str, config: Dict[str, Any]) -> str:
        value = str(location or "").strip()

        if not value:
            return ""

        cleanup_phrases = config.get("location_cleanup_phrases", [])
        stop_phrases = config.get("location_stop_phrases", [])
        max_words = config.get("location_max_words", 4)

        if not isinstance(cleanup_phrases, list):
            cleanup_phrases = []

        if not isinstance(stop_phrases, list):
            stop_phrases = []

        max_words_int = LocationSubagent.safe_int(max_words, 4)

        if max_words_int <= 0:
            max_words_int = 4

        for phrase in cleanup_phrases:
            phrase_text = str(phrase or "").strip()

            if not phrase_text:
                continue

            value = re.sub(
                re.escape(phrase_text),
                " ",
                value,
                flags=re.IGNORECASE
            )

        earliest_stop_index = None

        for phrase in stop_phrases:
            phrase_text = str(phrase or "").strip()

            if not phrase_text:
                continue

            match = re.search(
                re.escape(phrase_text),
                value,
                flags=re.IGNORECASE
            )

            if not match:
                continue

            if earliest_stop_index is None or match.start() < earliest_stop_index:
                earliest_stop_index = match.start()

        if earliest_stop_index is not None:
            value = value[:earliest_stop_index]

        separator_pattern = str(
            config.get("location_separator_pattern")
            or r"[،,.!?؟:;؛]+"
        )

        try:
            value = re.sub(separator_pattern, " ", value)
        except re.error:
            value = re.sub(r"\s+", " ", value)

        value = re.sub(r"\s+", " ", value).strip()

        words = value.split()

        if len(words) > max_words_int:
            value = " ".join(words[:max_words_int]).strip()

        return value

    def template_label(self, config: Dict[str, Any], key: str) -> str:
        templates = config.get("templates", {})

        if isinstance(templates, dict):
            value = str(templates.get(key, "") or "").strip()
            if value:
                return value

        fallback_prefix = str(config.get("template_fallback_prefix", "") or "").strip()
        key_text = str(key or "").strip()

        if fallback_prefix and key_text:
            return f"{fallback_prefix}{key_text}".upper()

        return key_text.upper()

    @staticmethod
    def config_list(config: Dict[str, Any], key: str) -> List[Any]:
        value = config.get(key, [])

        if isinstance(value, list):
            return value

        if value in [None, ""]:
            return []

        return [value]

    @staticmethod
    def first_present_from_result(tool_result: Dict[str, Any], paths: List[Any]) -> Any:
        for path in paths:
            path_text = str(path or "").strip()
            if not path_text:
                continue

            value = deep_get(tool_result, path_text)

            if value not in [None, "", [], {}]:
                return value

        return ""

    @staticmethod
    def first_present_from_variables(variables: Dict[str, Any], paths: List[Any]) -> Any:
        for path in paths:
            path_text = str(path or "").strip()
            if not path_text:
                continue

            value = deep_get(variables, path_text)

            if value not in [None, "", [], {}]:
                return value

        return ""

    @staticmethod
    def apply_configured_updates(
        variables: Dict[str, Any],
        config: Dict[str, Any],
        key: str
    ) -> Dict[str, Any]:
        updates = config.get(key, {})

        if not isinstance(updates, dict):
            updates = {}

        return apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=[]
        )

    @staticmethod
    def safe_int(value: Any, default: int) -> int:
        try:
            return int(value)
        except Exception:
            return default
