import re
from typing import Any, Dict, List

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_tool_update_rules,
    apply_variable_patch,
    compact_dict,
    deep_get,
    get_subagent_config,
    matches_any,
    render_template
)


class LocationSubagent:
    """
    Location executor for the LangGraph architecture.

    Responsibilities:
    - detect/extract user location text if present
    - use already-provided coordinates if present
    - ask for location only when nearest branch is requested and no location exists
    - call find_nearest_branch
    - update source-of-truth branch variables only from tool results

    Not responsible for final customer-facing wording.
    Final wording is generated by graph.response_node and validated by quality_guard.
    """

    name = "location"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {})
        observations: List[Dict[str, Any]] = []

        location = self.extract_location(
            message=context.user_message,
            config=config,
            normalization=normalization
        )

        coordinates = self.extract_coordinates(variables)

        nearest_requested = matches_any(
            context.user_message,
            config.get("nearest_branch_request_phrases", []),
            normalization
        )

        if not location and not coordinates:
            if nearest_requested or self.location_flow_active(variables, config):
                updates = config.get("on_nearest_branch_request_updates", {})

                patched_variables = apply_variable_patch(
                    variables=variables,
                    updates=updates if isinstance(updates, dict) else {},
                    clear=[]
                )

                answer = render_template(
                    config.get("templates", {}).get(
                        "ask_location_for_nearest_branch",
                        "LOCATION_NEEDED_FOR_NEAREST_BRANCH"
                    ),
                    {
                        "variables": patched_variables,
                        "message": context.user_message
                    }
                )

                return SubagentResult(
                    handled=True,
                    action="ask_user",
                    answer=answer,
                    variable_updates=patched_variables,
                    observations=observations,
                    selected_subagent=self.name,
                    tool_calls_used=0,
                    notes="nearest branch requested without location"
                )

            return SubagentResult(handled=False)

        tool_name = config.get("tool_name", "")
        operation = config.get("operation", "find_nearest_branch")

        arguments: Dict[str, Any] = {}

        if location:
            arguments[config.get("location_argument", "location")] = location

        if coordinates:
            arguments["latitude"] = coordinates.get("latitude")
            arguments["longitude"] = coordinates.get("longitude")

        tool_result = context.tool_runner.call(
            tool_name=tool_name,
            operation=operation,
            arguments=compact_dict(arguments)
        )

        observations.append({
            "subagent": self.name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        manual_updates = self.build_manual_updates(
            config=config,
            variables=updated_variables,
            location=location,
            coordinates=coordinates,
            tool_result=tool_result
        )

        updated_variables = apply_variable_patch(
            variables=updated_variables,
            updates=manual_updates,
            clear=[]
        )

        answer = render_template(
            self.result_label(config, tool_result),
            {
                "variables": updated_variables,
                "result": tool_result,
                "arguments": arguments,
                "location": location,
                "coordinates": coordinates,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="reply",
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=1,
            notes="location resolved"
        )

    def build_manual_updates(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        location: str,
        coordinates: Dict[str, Any],
        tool_result: Dict[str, Any]
    ) -> Dict[str, Any]:
        updates: Dict[str, Any] = {}

        if not isinstance(tool_result, dict):
            return updates

        if tool_result.get("ok") is True:
            user_area = (
                tool_result.get("user_area")
                or tool_result.get("location")
                or location
                or deep_get(variables, "user_area")
            )

            if user_area:
                updates[config.get("user_area_path", "user_area")] = self.cleanup_location(
                    user_area,
                    config
                )

            if coordinates:
                updates["user_coordinates.latitude"] = coordinates.get("latitude")
                updates["user_coordinates.longitude"] = coordinates.get("longitude")

        if tool_result.get("branch_found") is True:
            branch = (
                tool_result.get("branch")
                or tool_result.get("nearest_branch")
                or tool_result.get("location_branch")
            )

            if branch:
                updates[config.get("nearest_branch_path", "nearest_branch")] = branch
                updates[config.get("location_branch_path", "location_branch")] = branch

                if config.get("set_selected_branch_on_match", True):
                    updates[config.get("selected_branch_path", "selected_branch")] = branch

        return updates

    def result_label(self, config: Dict[str, Any], tool_result: Dict[str, Any]) -> str:
        templates = config.get("templates", {})

        if not isinstance(tool_result, dict):
            return templates.get("tool_error", "LOCATION_TOOL_ERROR")

        if tool_result.get("ok") is False:
            return templates.get("tool_error", "LOCATION_TOOL_ERROR")

        if tool_result.get("branch_found") is True:
            return templates.get("branch_found", "LOCATION_NEAREST_BRANCH_FOUND")

        return templates.get("branch_not_found", "LOCATION_BRANCH_NOT_FOUND")

    def extract_location(
        self,
        message: str,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> str:
        raw_message = str(message or "").strip()

        patterns = config.get("location_patterns", [])

        if isinstance(patterns, list):
            for item in patterns:
                if not isinstance(item, dict):
                    continue

                regex = item.get("regex", "")
                group = int(item.get("group", 1))

                if not regex:
                    continue

                try:
                    match = re.search(regex, raw_message, flags=re.IGNORECASE)
                except re.error:
                    continue

                if match:
                    value = match.group(group).strip()
                    value = self.cleanup_location(value, config)
                    if value:
                        return value

        trigger_phrases = config.get("location_trigger_phrases", [])

        if matches_any(raw_message, trigger_phrases, normalization):
            cleaned = raw_message

            if isinstance(trigger_phrases, list):
                for phrase in trigger_phrases:
                    escaped = re.escape(str(phrase))
                    cleaned = re.sub(escaped, " ", cleaned, flags=re.IGNORECASE)

            cleaned = self.cleanup_location(cleaned, config)

            if cleaned:
                return cleaned

        return ""

    def extract_coordinates(self, variables: Dict[str, Any]) -> Dict[str, Any]:
        raw_lat = (
            deep_get(variables, "latitude")
            or deep_get(variables, "lat")
            or deep_get(variables, "location.latitude")
            or deep_get(variables, "user_location.latitude")
            or deep_get(variables, "user_coordinates.latitude")
        )

        raw_lng = (
            deep_get(variables, "longitude")
            or deep_get(variables, "lng")
            or deep_get(variables, "lon")
            or deep_get(variables, "location.longitude")
            or deep_get(variables, "user_location.longitude")
            or deep_get(variables, "user_coordinates.longitude")
        )

        if raw_lat in [None, ""] or raw_lng in [None, ""]:
            return {}

        try:
            lat = float(raw_lat)
            lng = float(raw_lng)
        except Exception:
            return {}

        if lat < -90 or lat > 90 or lng < -180 or lng > 180:
            return {}

        return {
            "latitude": lat,
            "longitude": lng
        }

    def location_flow_active(self, variables: Dict[str, Any], config: Dict[str, Any]) -> bool:
        intent_path = config.get("location_intent_path", "location.intent")
        intent = str(deep_get(variables, intent_path, "") or "").strip()

        return intent in {
            "nearest_branch",
            "find_nearest_branch",
            "branch_locator"
        }

    @staticmethod
    def cleanup_location(location: str, config: Dict[str, Any]) -> str:
        value = str(location or "").strip()

        if not value:
            return ""

        cleanup_phrases = config.get("location_cleanup_phrases", [])
        stop_phrases = config.get("location_stop_phrases", [])
        max_words = config.get("location_max_words", 4)

        if not isinstance(cleanup_phrases, list):
            cleanup_phrases = []

        if not isinstance(stop_phrases, list):
            stop_phrases = []

        try:
            max_words_int = int(max_words)
        except Exception:
            max_words_int = 4

        if max_words_int <= 0:
            max_words_int = 4

        # Remove leading location trigger phrases, e.g. "انا ساكن في العبور" -> "العبور".
        for phrase in cleanup_phrases:
            phrase_text = str(phrase or "").strip()

            if not phrase_text:
                continue

            value = re.sub(
                re.escape(phrase_text),
                " ",
                value,
                flags=re.IGNORECASE
            )

        # Cut everything after configured stop phrases.
        # Example:
        # "العبور قولي اقرب فرع ليا وايه المواعيد المتاحه يوم الاحد الجاي"
        # -> "العبور"
        earliest_stop_index = None

        for phrase in stop_phrases:
            phrase_text = str(phrase or "").strip()

            if not phrase_text:
                continue

            match = re.search(
                re.escape(phrase_text),
                value,
                flags=re.IGNORECASE
            )

            if not match:
                continue

            if earliest_stop_index is None or match.start() < earliest_stop_index:
                earliest_stop_index = match.start()

        if earliest_stop_index is not None:
            value = value[:earliest_stop_index]

        # Remove obvious separators/noise after stop trimming.
        value = re.sub(r"[،,.!?؟:;؛]+", " ", value)
        value = re.sub(r"\s+", " ", value).strip()

        # If the extracted value is still too long, keep only the first few words.
        # The exact limit is controlled by domain_bundle.json through location_max_words.
        words = value.split()

        if len(words) > max_words_int:
            value = " ".join(words[:max_words_int]).strip()

        return value
