from typing import Any, Dict, List

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_tool_update_rules,
    compact_dict,
    matches_any,
    render_template
)


class LookupSubagent:
    """
    Lookup executor for the LangGraph architecture.

    Responsibilities:
    - execute safe read-only lookup operations when a configured rule clearly matches
    - call configured lookup tools
    - apply tool update rules
    - return grounded observations

    Not responsible for final customer-facing wording.
    Final wording is generated by graph.response_node and validated by quality_guard.
    """

    name = "lookup"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return assistant_config.get("subagents", {}).get(self.name, {})

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {})
        observations: List[Dict[str, Any]] = []

        rules = config.get("rules", [])

        if not isinstance(rules, list) or not rules:
            return SubagentResult(handled=False)

        matched_rule = self.find_matching_rule(
            message=context.user_message,
            rules=rules,
            normalization=normalization
        )

        if not matched_rule:
            return SubagentResult(handled=False)

        tool_name = matched_rule.get("tool_name") or config.get("default_tool_name", "")
        operation = matched_rule.get("operation", "")
        arguments = matched_rule.get("arguments", {})

        if not isinstance(arguments, dict):
            arguments = {}

        try:
            tool_result = context.tool_runner.call(
                tool_name=tool_name,
                operation=operation,
                arguments=compact_dict(arguments)
            )
        except Exception as exc:
            tool_result = {
                "ok": False,
                "operation": operation,
                "error": f"{type(exc).__name__}: {exc}"
            }

        observations.append({
            "subagent": self.name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        template = (
            matched_rule.get("success_template", "LOOKUP_RESULT")
            if tool_result.get("ok") is not False
            else matched_rule.get("error_template", "LOOKUP_ERROR")
        )

        answer = render_template(template, {
            "variables": updated_variables,
            "result": tool_result,
            "arguments": arguments,
            "message": context.user_message
        })

        return SubagentResult(
            handled=True,
            action="reply",
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=1,
            notes=f"executed lookup rule {matched_rule.get('id', '')}"
        )

    def find_matching_rule(
        self,
        message: str,
        rules: List[Dict[str, Any]],
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        for rule in rules:
            if not isinstance(rule, dict):
                continue

            phrases = rule.get("phrases", [])

            if not isinstance(phrases, list):
                phrases = []

            if matches_any(message, phrases, normalization):
                return rule

        return {}
