from typing import Any, Dict, List, Optional

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_tool_update_rules,
    apply_variable_patch,
    build_object_from_mapping,
    compact_dict,
    deep_get,
    get_subagent_config,
    matches_any,
    render_template
)


class LookupSubagent:
    """
    Lookup executor for the LangGraph architecture.

    Responsibilities:
    - execute configured read-only lookup operations when a configured rule clearly matches
    - call configured lookup tools
    - apply configured tool update rules and optional rule-level update mappings
    - return grounded observations and internal answer labels/draft signals

    Architecture boundaries:
    - This executor is deterministic and config-driven.
    - It does not own final customer-facing wording.
    - It must not contain domain/customer phrase hardcoding.
    - Final wording is generated by graph.response_node and validated by quality_guard.
    """

    name = "lookup"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not self.is_enabled(config):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {}) or {}
        observations: List[Dict[str, Any]] = []

        rules = self.get_rules(config)

        if not rules:
            return SubagentResult(handled=False)

        matched_rule = self.find_matching_rule(
            message=context.user_message,
            rules=rules,
            variables=variables,
            normalization=normalization,
            config=config
        )

        if not matched_rule:
            return SubagentResult(handled=False)

        if self.rule_requires_known_context(
            rule=matched_rule,
            variables=variables
        ) is False:
            answer = render_template(
                self.get_rule_template(
                    rule=matched_rule,
                    config=config,
                    template_key="missing_context_template",
                    default_template_key="missing_context"
                ),
                {
                    "variables": variables,
                    "rule": matched_rule,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action=self.get_rule_action(matched_rule, config, "ask_user"),
                answer=answer,
                variable_updates=variables,
                observations=observations,
                selected_subagent=self.name,
                tool_calls_used=0,
                notes=self.build_note(config, "missing_context", matched_rule)
            )

        tool_name = self.get_tool_name(config, matched_rule)
        operation = self.get_operation(matched_rule)
        arguments = self.build_arguments(
            rule=matched_rule,
            variables=variables,
            message=context.user_message
        )

        if not tool_name or not operation:
            answer = render_template(
                self.get_rule_template(
                    rule=matched_rule,
                    config=config,
                    template_key="invalid_rule_template",
                    default_template_key="invalid_rule"
                ),
                {
                    "variables": variables,
                    "rule": matched_rule,
                    "arguments": arguments,
                    "message": context.user_message
                }
            )

            return SubagentResult(
                handled=True,
                action=self.get_rule_action(matched_rule, config, "reply"),
                answer=answer,
                variable_updates=variables,
                observations=observations,
                selected_subagent=self.name,
                tool_calls_used=0,
                notes=self.build_note(config, "invalid_rule", matched_rule)
            )

        try:
            tool_result = context.tool_runner.call(
                tool_name=tool_name,
                operation=operation,
                arguments=compact_dict(arguments)
            )
        except Exception as exc:
            tool_result = self.build_tool_error_result(
                config=config,
                rule=matched_rule,
                operation=operation,
                exc=exc
            )

        observations.append({
            "subagent": self.name,
            "rule_id": matched_rule.get("id", ""),
            "tool_name": tool_name,
            "operation": operation,
            "arguments": arguments,
            "result": tool_result
        })

        updated_variables = apply_tool_update_rules(
            assistant_config=context.assistant_config,
            variables=variables,
            operation=operation,
            arguments=arguments,
            result=tool_result
        )

        updated_variables = self.apply_rule_update_mappings(
            variables=updated_variables,
            rule=matched_rule,
            tool_result=tool_result,
            arguments=arguments,
            message=context.user_message
        )

        template = self.result_template(
            config=config,
            rule=matched_rule,
            tool_result=tool_result
        )

        answer = render_template(template, {
            "variables": updated_variables,
            "result": tool_result,
            "arguments": arguments,
            "rule": matched_rule,
            "message": context.user_message
        })

        return SubagentResult(
            handled=True,
            action=self.get_rule_action(matched_rule, config, "reply"),
            answer=answer,
            variable_updates=updated_variables,
            observations=observations,
            selected_subagent=self.name,
            tool_calls_used=1,
            notes=self.build_note(config, "executed", matched_rule)
        )

    def is_enabled(self, config: Dict[str, Any]) -> bool:
        return bool(config.get("enabled", False))

    def get_rules(self, config: Dict[str, Any]) -> List[Dict[str, Any]]:
        rules = config.get("rules", [])

        if not isinstance(rules, list):
            return []

        return [rule for rule in rules if isinstance(rule, dict)]

    def find_matching_rule(
        self,
        message: str,
        rules: List[Dict[str, Any]],
        variables: Dict[str, Any],
        normalization: Dict[str, Any],
        config: Dict[str, Any]
    ) -> Dict[str, Any]:
        for rule in rules:
            if not self.rule_enabled(rule):
                continue

            if not self.rule_matches_message(
                message=message,
                rule=rule,
                normalization=normalization
            ):
                continue

            if not self.rule_matches_variable_conditions(
                rule=rule,
                variables=variables
            ):
                continue

            if not self.rule_allowed_by_config(
                rule=rule,
                config=config,
                variables=variables
            ):
                continue

            return rule

        return {}

    def rule_enabled(self, rule: Dict[str, Any]) -> bool:
        return bool(rule.get("enabled", True))

    def rule_matches_message(
        self,
        message: str,
        rule: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        phrases = rule.get("phrases", [])

        if isinstance(phrases, list) and phrases:
            if matches_any(message, phrases, normalization):
                return True

        any_phrases = rule.get("any_phrases", [])

        if isinstance(any_phrases, list) and any_phrases:
            if matches_any(message, any_phrases, normalization):
                return True

        all_required_phrases = rule.get("all_required_phrases", [])

        if isinstance(all_required_phrases, list) and all_required_phrases:
            return all(
                matches_any(message, [phrase], normalization)
                for phrase in all_required_phrases
                if str(phrase or "").strip()
            )

        # If a rule explicitly declares it can be selected by manifest/subagent
        # without phrase matching, let graph routing choose it. This stays
        # config-driven and avoids domain logic in Python.
        return bool(rule.get("allow_without_phrase_match", False))

    def rule_matches_variable_conditions(
        self,
        rule: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        conditions = rule.get("variable_conditions", [])

        if not isinstance(conditions, list):
            return True

        for condition in conditions:
            if not isinstance(condition, dict):
                continue

            path = str(condition.get("path") or "").strip()

            if not path:
                continue

            current = deep_get(variables, path)
            expected_exists = condition.get("exists")

            if expected_exists is True and current in [None, "", [], {}]:
                return False

            if expected_exists is False and current not in [None, "", [], {}]:
                return False

            if "equals" in condition and current != condition.get("equals"):
                return False

            if "not_equals" in condition and current == condition.get("not_equals"):
                return False

            allowed_values = condition.get("in")
            if isinstance(allowed_values, list) and current not in allowed_values:
                return False

            disallowed_values = condition.get("not_in")
            if isinstance(disallowed_values, list) and current in disallowed_values:
                return False

        return True

    def rule_allowed_by_config(
        self,
        rule: Dict[str, Any],
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        allow_config = config.get("allow_rules", {})

        if not isinstance(allow_config, dict):
            return True

        required_rule_ids = allow_config.get("only_rule_ids")

        if isinstance(required_rule_ids, list) and required_rule_ids:
            if rule.get("id") not in required_rule_ids:
                return False

        blocked_rule_ids = allow_config.get("blocked_rule_ids")

        if isinstance(blocked_rule_ids, list) and rule.get("id") in blocked_rule_ids:
            return False

        required_paths = allow_config.get("required_paths")

        if isinstance(required_paths, list):
            for path in required_paths:
                if deep_get(variables, str(path or "")) in [None, "", [], {}]:
                    return False

        return True

    def rule_requires_known_context(
        self,
        rule: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        required_context_paths = rule.get("required_context_paths", [])

        if not isinstance(required_context_paths, list) or not required_context_paths:
            return True

        return all(
            deep_get(variables, str(path or "")) not in [None, "", [], {}]
            for path in required_context_paths
            if str(path or "").strip()
        )

    def get_tool_name(self, config: Dict[str, Any], rule: Dict[str, Any]) -> str:
        return str(
            rule.get("tool_name")
            or config.get("default_tool_name")
            or config.get("tool_name")
            or ""
        ).strip()

    def get_operation(self, rule: Dict[str, Any]) -> str:
        return str(rule.get("operation") or "").strip()

    def build_arguments(
        self,
        rule: Dict[str, Any],
        variables: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        arguments = rule.get("arguments", {})

        if not isinstance(arguments, dict):
            arguments = {}

        arguments_mapping = rule.get("arguments_mapping", {})

        if isinstance(arguments_mapping, dict) and arguments_mapping:
            mapped = build_object_from_mapping(arguments_mapping, {
                "variables": variables,
                "message": message,
                "rule": rule
            })

            if isinstance(mapped, dict):
                merged = dict(arguments)
                merged.update(mapped)
                arguments = merged

        return arguments

    def build_tool_error_result(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        operation: str,
        exc: Exception
    ) -> Dict[str, Any]:
        error_config = config.get("tool_error_result", {})

        if not isinstance(error_config, dict):
            error_config = {}

        include_exception_type = bool(error_config.get("include_exception_type", True))
        error_text = str(exc)

        if include_exception_type:
            error_text = f"{type(exc).__name__}: {exc}"

        return {
            "ok": False,
            "operation": operation,
            "rule_id": rule.get("id", ""),
            "error": error_text
        }

    def apply_rule_update_mappings(
        self,
        variables: Dict[str, Any],
        rule: Dict[str, Any],
        tool_result: Dict[str, Any],
        arguments: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        updates: Dict[str, Any] = {}

        update_mappings = rule.get("update_mappings", {})

        if isinstance(update_mappings, dict) and update_mappings:
            mapped = build_object_from_mapping(update_mappings, {
                "variables": variables,
                "result": tool_result,
                "arguments": arguments,
                "rule": rule,
                "message": message
            })

            if isinstance(mapped, dict):
                updates.update(mapped)

        static_updates = rule.get("variable_updates", {})
        if isinstance(static_updates, dict):
            updates.update(static_updates)

        clear = rule.get("clear_variables", [])
        if not isinstance(clear, list):
            clear = []

        if not updates and not clear:
            return variables

        return apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=clear
        )

    def result_template(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        tool_result: Dict[str, Any]
    ) -> str:
        ok_path = str(config.get("result_ok_path") or "ok").strip()
        ok_value = config.get("result_ok_value", True)

        result_ok = deep_get(tool_result, ok_path)

        success = result_ok is not False

        if ok_path and result_ok is not None:
            success = result_ok == ok_value

        if success:
            return self.get_rule_template(
                rule=rule,
                config=config,
                template_key="success_template",
                default_template_key="success"
            )

        return self.get_rule_template(
            rule=rule,
            config=config,
            template_key="error_template",
            default_template_key="error"
        )

    def get_rule_template(
        self,
        rule: Dict[str, Any],
        config: Dict[str, Any],
        template_key: str,
        default_template_key: str
    ) -> str:
        template = str(rule.get(template_key) or "").strip()

        if template:
            return template

        templates = config.get("templates", {})
        if not isinstance(templates, dict):
            templates = {}

        if default_template_key in templates:
            return str(templates.get(default_template_key) or "").strip()

        fallback_prefix = str(config.get("template_fallback_prefix") or self.name).strip().upper()
        fallback_suffix = str(default_template_key or template_key or "result").strip().upper()

        return f"{fallback_prefix}_{fallback_suffix}"

    def get_rule_action(
        self,
        rule: Dict[str, Any],
        config: Dict[str, Any],
        default_action: str
    ) -> str:
        action = str(rule.get("action") or "").strip()

        if action:
            return action

        action_map = config.get("actions", {})

        if isinstance(action_map, dict):
            configured = str(action_map.get(default_action) or "").strip()
            if configured:
                return configured

        return default_action

    def build_note(
        self,
        config: Dict[str, Any],
        event: str,
        rule: Optional[Dict[str, Any]] = None
    ) -> str:
        notes_config = config.get("notes", {})

        if isinstance(notes_config, dict):
            template = str(notes_config.get(event) or "").strip()

            if template:
                return template.format(
                    rule_id=(rule or {}).get("id", ""),
                    subagent=self.name,
                    event=event
                )

        return f"{self.name}:{event}:{(rule or {}).get('id', '')}"
