import re
from typing import Any, Dict, List, Optional, Tuple

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_variable_patch,
    deep_get,
    get_subagent_config,
    matches_any,
    render_template
)


class TroubleshootingSubagent:
    """
    Config-driven troubleshooting executor for the LangGraph architecture.

    Responsibilities:
    - detect one or more symptom/problem categories from configured rules
    - score matching rules instead of taking the first weak match
    - maintain lightweight diagnostic state through configured paths
    - avoid hijacking active booking/location/handoff flows
    - stop diagnostics and yield to visit/booking flows when configured intent appears
    - support hesitant/complex users who provide several symptoms or change symptom focus
    - return internal draft labels only

    Not responsible for final customer-facing wording.
    Final diagnostic wording is generated by graph.response_node and validated by quality_guard.

    Architecture rule:
    - No customer-facing/domain phrase hardcoding in Python.
    - Symptoms, booking/visit phrases, templates, phase policy, mappings, and clear paths live in domain_bundle.json.
    """

    name = "troubleshooting"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {}) or {}

        if self.should_not_take_over(context, config, normalization):
            return SubagentResult(handled=False)

        if self.should_skip_due_to_existing_paths(config, variables):
            return SubagentResult(handled=False)

        if self.visit_or_next_action_intent(context, config, normalization):
            return self.handle_visit_or_next_action_intent(
                context=context,
                config=config,
                variables=variables
            )

        active_result = self.continue_active_troubleshooting_if_any(
            context=context,
            config=config,
            variables=variables
        )

        if active_result.handled:
            return active_result

        matched_rules = self.find_matching_rules(
            config=config,
            message=context.user_message,
            normalization=normalization,
            variables=variables
        )

        if not matched_rules:
            return SubagentResult(handled=False)

        primary_rule = matched_rules[0]["rule"]

        return self.start_rule(
            context=context,
            config=config,
            variables=variables,
            rule=primary_rule,
            matched_rules=matched_rules
        )

    # ------------------------------------------------------------------
    # Ownership / takeover protection
    # ------------------------------------------------------------------

    def should_not_take_over(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        takeover_config = config.get("do_not_take_over", {})
        if not isinstance(takeover_config, dict):
            takeover_config = {}

        phrase_sources: List[Any] = [
            config.get("direct_booking_phrases", []),
            takeover_config.get("phrases", []),
            takeover_config.get("intent_phrases", []),
        ]

        phrases = self.flatten_phrase_sources(phrase_sources)

        if phrases and matches_any(context.user_message, phrases, normalization):
            return True

        variable_conditions = takeover_config.get("variable_conditions", [])
        if isinstance(variable_conditions, list):
            for condition in variable_conditions:
                if self.condition_matches(condition, context.variables or {}, context=context):
                    return True

        active_owner_config = takeover_config.get("active_owner_paths", [])
        if isinstance(active_owner_config, list):
            for path in active_owner_config:
                if deep_get(context.variables or {}, str(path or "").strip()) not in [None, "", [], {}]:
                    return True

        return False

    def should_skip_due_to_existing_paths(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        for path in config.get("skip_if_paths_exist", []) or []:
            current = deep_get(variables, str(path))

            if current not in [None, "", [], {}]:
                return True

        conditions = config.get("skip_conditions", [])
        if isinstance(conditions, list):
            for condition in conditions:
                if self.condition_matches(condition, variables):
                    return True

        return False

    def visit_or_next_action_intent(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        intent_config = config.get("visit_or_next_action_intent", {})
        if not isinstance(intent_config, dict):
            intent_config = {}

        phrases = self.flatten_phrase_sources([
            intent_config.get("phrases", []),
            config.get("direct_booking_phrases", []),
            config.get("inspection_request_phrases", []),
        ])

        if phrases and matches_any(context.user_message, phrases, normalization):
            return True

        conditions = intent_config.get("conditions", [])
        if isinstance(conditions, list):
            for condition in conditions:
                if self.condition_matches(condition, context.variables or {}, context=context):
                    return True

        return False

    def handle_visit_or_next_action_intent(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> SubagentResult:
        phase = str(
            self.config_path(config, "visit_or_next_action_intent.phase", "")
            or "visit_requested"
        )

        updates = {}
        updates.update(self.phase_updates(config, phase))
        updates.update(self.config_dict(config, "visit_or_next_action_intent.updates"))
        updates.update(self.config_dict(config, "visit_intent_updates"))

        clear = self.config_list(config, "visit_or_next_action_intent.clear")
        clear.extend(self.config_list(config, "visit_intent_clear"))

        patched = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=clear,
            assistant_config=context.assistant_config,
            allow_empty_updates=True
        )

        answer = render_template(
            self.phase_label(config, phase),
            {
                "variables": patched,
                "phase": phase,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action=self.phase_action(config, phase),
            answer=answer,
            variable_updates=updates,
            clear_variables=clear,
            selected_subagent=self.name,
            notes=self.build_note(config, phase, {}, {})
        )

    # ------------------------------------------------------------------
    # Active flow handling
    # ------------------------------------------------------------------

    def continue_active_troubleshooting_if_any(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> SubagentResult:
        state_path = str(config.get("state_path", "troubleshooting.stage") or "troubleshooting.stage")
        count_path = str(config.get("count_path", "troubleshooting.diagnostic_count") or "troubleshooting.diagnostic_count")
        selected_rule_path = str(config.get("selected_rule_path", "troubleshooting.selected_rule_id") or "troubleshooting.selected_rule_id")

        current_state = str(deep_get(variables, state_path, "") or "").strip()
        selected_rule_id = str(deep_get(variables, selected_rule_path, "") or "").strip()

        if not selected_rule_id:
            return SubagentResult(handled=False)

        active_state_values = self.get_active_state_values(config)

        if current_state not in active_state_values:
            return SubagentResult(handled=False)

        normalization = context.assistant_config.get("normalization", {}) or {}

        if self.visit_or_next_action_intent(context, config, normalization):
            return self.handle_visit_or_next_action_intent(
                context=context,
                config=config,
                variables=variables
            )

        current_rule = self.find_rule(config, selected_rule_id)

        if not current_rule:
            return SubagentResult(handled=False)

        if self.get_config_bool(config, "allow_rule_switch_during_active", True):
            matched_rules = self.find_matching_rules(
                config=config,
                message=context.user_message,
                normalization=normalization,
                variables=variables
            )
            if matched_rules:
                best_rule = matched_rules[0]["rule"]
                best_rule_id = str(best_rule.get("id", "") or "").strip()

                if best_rule_id and best_rule_id != selected_rule_id:
                    switch_margin = self.safe_float(config.get("rule_switch_score_margin", 0.0), 0.0)
                    selected_score = self.score_rule(
                        rule=current_rule,
                        config=config,
                        message=context.user_message,
                        normalization=normalization,
                        variables=variables
                    )
                    if float(matched_rules[0].get("score", 0.0) or 0.0) >= selected_score + switch_margin:
                        return self.start_rule(
                            context=context,
                            config=config,
                            variables=variables,
                            rule=best_rule,
                            matched_rules=matched_rules,
                            phase_override="switched"
                        )

        current_count = deep_get(variables, count_path, 0)

        try:
            current_count_int = int(current_count or 0)
        except Exception:
            current_count_int = 0

        return self.continue_rule(
            context=context,
            config=config,
            variables=variables,
            rule=current_rule,
            current_count=current_count_int
        )

    # ------------------------------------------------------------------
    # Rule lifecycle
    # ------------------------------------------------------------------

    def start_rule(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        rule: Dict[str, Any],
        matched_rules: Optional[List[Dict[str, Any]]] = None,
        phase_override: str = ""
    ) -> SubagentResult:
        state_path = str(config.get("state_path", "troubleshooting.stage") or "troubleshooting.stage")
        count_path = str(config.get("count_path", "troubleshooting.diagnostic_count") or "troubleshooting.diagnostic_count")
        selected_rule_path = str(config.get("selected_rule_path", "troubleshooting.selected_rule_id") or "troubleshooting.selected_rule_id")
        active_state = str(config.get("active_state", "active") or "active")

        phase = phase_override or "started"

        updates: Dict[str, Any] = {}

        if isinstance(rule.get("variable_updates"), dict):
            updates.update(rule.get("variable_updates", {}))

        updates.update(self.build_rule_metadata_updates(config, rule, context.user_message))
        updates.update(self.build_matched_rules_updates(config, matched_rules or []))
        updates.update(self.phase_updates(config, phase, rule=rule))

        updates[state_path] = active_state
        updates[count_path] = 1
        updates[selected_rule_path] = rule.get("id", "")

        clear = self.config_list(rule, "clear_variables")
        clear.extend(self.config_list(config, f"phase_clears.{phase}"))

        patched = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=clear,
            assistant_config=context.assistant_config,
            allow_empty_updates=True
        )

        answer = render_template(
            self.rule_label(config, rule, phase),
            {
                "variables": patched,
                "rule": rule,
                "phase": phase,
                "message": context.user_message,
                "matched_rules": matched_rules or []
            }
        )

        return SubagentResult(
            handled=True,
            action=self.phase_action(config, phase),
            answer=answer,
            variable_updates=updates,
            clear_variables=clear,
            selected_subagent=self.name,
            notes=self.build_note(config, phase, rule, {"count": 1})
        )

    def continue_rule(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        rule: Dict[str, Any],
        current_count: int
    ) -> SubagentResult:
        state_path = str(config.get("state_path", "troubleshooting.stage") or "troubleshooting.stage")
        count_path = str(config.get("count_path", "troubleshooting.diagnostic_count") or "troubleshooting.diagnostic_count")
        complete_state = str(config.get("complete_state", "complete") or "complete")
        active_state = str(config.get("active_state", "active") or "active")

        max_diagnostic_turns = self.safe_int(
            rule.get("max_diagnostic_turns_before_visit_offer", config.get("max_diagnostic_turns_before_visit_offer", 2)),
            2
        )

        next_count = max(0, int(current_count or 0)) + 1

        updates: Dict[str, Any] = {}
        updates[count_path] = next_count
        updates.update(self.build_latest_answer_updates(config, context.user_message))
        updates.update(self.build_history_updates(config, variables, context.user_message))

        phase = self.choose_continue_phase(
            config=config,
            rule=rule,
            next_count=next_count,
            max_diagnostic_turns=max_diagnostic_turns,
            variables=variables,
            message=context.user_message
        )

        if phase == "complete":
            updates[state_path] = complete_state
            inspection_path = str(
                rule.get("inspection_recommended_path", "")
                or config.get("inspection_recommended_path", "")
                or self.config_path(config, "phase_updates.complete.inspection_recommended_path", "")
                or "troubleshooting.inspection_recommended"
            )
            if inspection_path:
                updates[inspection_path] = True
        else:
            updates[state_path] = active_state

        updates.update(self.phase_updates(config, phase, rule=rule))

        clear = self.config_list(config, f"phase_clears.{phase}")
        clear.extend(self.config_list(rule, f"phase_clears.{phase}"))

        patched = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=clear,
            assistant_config=context.assistant_config,
            allow_empty_updates=True
        )

        answer = render_template(
            self.rule_label(config, rule, phase),
            {
                "variables": patched,
                "rule": rule,
                "phase": phase,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action=self.phase_action(config, phase),
            answer=answer,
            variable_updates=updates,
            clear_variables=clear,
            selected_subagent=self.name,
            notes=self.build_note(config, phase, rule, {"count": next_count})
        )

    def choose_continue_phase(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        next_count: int,
        max_diagnostic_turns: int,
        variables: Dict[str, Any],
        message: str
    ) -> str:
        phase_rules = config.get("continue_phase_rules", [])
        if not isinstance(phase_rules, list):
            phase_rules = []

        for phase_rule in phase_rules:
            if not isinstance(phase_rule, dict):
                continue

            conditions = phase_rule.get("conditions", [])
            if isinstance(conditions, list) and conditions:
                context = {
                    "variables": variables,
                    "rule": rule,
                    "message": message,
                    "next_count": next_count,
                    "max_diagnostic_turns": max_diagnostic_turns
                }
                if all(self.condition_matches(item, variables, context=context) for item in conditions if isinstance(item, dict)):
                    phase = str(phase_rule.get("phase") or "").strip()
                    if phase:
                        return phase

        if next_count >= max_diagnostic_turns:
            return "complete"

        return "continued"

    # ------------------------------------------------------------------
    # Updates / mappings
    # ------------------------------------------------------------------

    def build_rule_metadata_updates(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        mappings = config.get("metadata_update_mappings", [])

        if not isinstance(mappings, list) or not mappings:
            base_path = str(config.get("metadata_path", "troubleshooting") or "troubleshooting")
            mappings = [
                {"target": f"{base_path}.last_user_symptom", "source": "message"},
                {"target": f"{base_path}.category", "source": "rule.category"},
                {"target": f"{base_path}.rule_id", "source": "rule.id"},
                {"target": f"{base_path}.expected_system", "source": "rule.expected_system"},
                {"target": f"{base_path}.possible_causes", "source": "rule.possible_causes", "default": []},
                {"target": f"{base_path}.recommended_questions", "source": "rule.recommended_questions", "default": []},
                {"target": "service_needed", "source": "rule.service_needed"},
            ]

        return self.build_updates_from_mappings(
            mappings=mappings,
            context={
                "rule": rule,
                "message": message
            }
        )

    def build_matched_rules_updates(
        self,
        config: Dict[str, Any],
        matched_rules: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        if not matched_rules:
            return {}

        updates: Dict[str, Any] = {}

        path = str(config.get("matched_rules_path", "troubleshooting.matched_rules") or "").strip()
        if path:
            updates[path] = [
                {
                    "id": str(item.get("rule", {}).get("id", "") or ""),
                    "score": float(item.get("score", 0.0) or 0.0),
                    "matched": item.get("matched", {})
                }
                for item in matched_rules
            ]

        primary_score_path = str(config.get("primary_score_path", "troubleshooting.primary_rule_score") or "").strip()
        if primary_score_path:
            updates[primary_score_path] = float(matched_rules[0].get("score", 0.0) or 0.0)

        return updates

    def build_latest_answer_updates(self, config: Dict[str, Any], message: str) -> Dict[str, Any]:
        mappings = config.get("latest_answer_update_mappings", [])

        if not isinstance(mappings, list) or not mappings:
            base_path = str(config.get("metadata_path", "troubleshooting") or "troubleshooting")
            mappings = [
                {"target": f"{base_path}.last_user_answer", "source": "message"}
            ]

        return self.build_updates_from_mappings(
            mappings=mappings,
            context={"message": message}
        )

    def build_history_updates(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        history_config = config.get("history", {})
        if not isinstance(history_config, dict) or not history_config.get("enabled", False):
            return {}

        path = str(history_config.get("path", "troubleshooting.history") or "").strip()
        if not path:
            return {}

        max_items = self.safe_int(history_config.get("max_items", 8), 8)
        current = deep_get(variables, path, [])

        if not isinstance(current, list):
            current = []

        item = {
            "message": message
        }

        extra_mappings = history_config.get("item_mappings", [])
        if isinstance(extra_mappings, list) and extra_mappings:
            item.update(self.build_updates_from_mappings(
                mappings=extra_mappings,
                context={
                    "message": message,
                    "variables": variables
                }
            ))

        updated = current + [item]

        if max_items > 0:
            updated = updated[-max_items:]

        return {path: updated}

    def build_updates_from_mappings(
        self,
        mappings: List[Dict[str, Any]],
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        updates: Dict[str, Any] = {}

        for item in mappings:
            if not isinstance(item, dict):
                continue

            target = str(item.get("target", "") or "").strip()
            if not target:
                continue

            value = self.mapping_source_value(item, context)

            if value in [None, "", [], {}] and "default" in item:
                value = item.get("default")

            allow_empty = bool(item.get("allow_empty", False))

            if value in [None, "", [], {}] and not allow_empty:
                continue

            updates[target] = value

        return updates

    def mapping_source_value(self, mapping: Dict[str, Any], context: Dict[str, Any]) -> Any:
        if "literal" in mapping:
            return mapping.get("literal")

        if "template" in mapping:
            return render_template(str(mapping.get("template") or ""), context)

        if "first_present" in mapping:
            for source in self.config_list(mapping, "first_present"):
                value = self.resolve_context_path(str(source or ""), context)
                if value not in [None, "", [], {}]:
                    return value
            return None

        source = str(mapping.get("source", "") or "").strip()
        if not source:
            return None

        if source == "message":
            return context.get("message", "")

        return self.resolve_context_path(source, context)

    def resolve_context_path(self, source: str, context: Dict[str, Any]) -> Any:
        if not source:
            return None

        return deep_get(context, source)

    # ------------------------------------------------------------------
    # Labels / phase config
    # ------------------------------------------------------------------

    def rule_label(self, config: Dict[str, Any], rule: Dict[str, Any], phase: str) -> str:
        if isinstance(rule.get("templates"), dict):
            label = str(rule.get("templates", {}).get(phase, "") or "").strip()
            if label:
                return label

        configured_labels = config.get("phase_template_labels", {})
        if isinstance(configured_labels, dict):
            label = str(configured_labels.get(phase, "") or "").strip()
            if label:
                return label

        return self.phase_label(config, phase)

    def phase_label(self, config: Dict[str, Any], phase: str) -> str:
        templates = config.get("templates", {})
        if isinstance(templates, dict):
            label = str(templates.get(phase, "") or "").strip()
            if label:
                return label

        fallback_prefix = str(config.get("template_fallback_prefix", "TROUBLESHOOTING") or "TROUBLESHOOTING")
        fallback_suffix = str(config.get("template_fallback_suffix", "") or "").strip()
        parts = [fallback_prefix, phase]
        if fallback_suffix:
            parts.append(fallback_suffix)
        return "_".join(parts).upper()

    def phase_action(self, config: Dict[str, Any], phase: str) -> str:
        actions = config.get("phase_actions", {})
        if isinstance(actions, dict):
            action = str(actions.get(phase, "") or "").strip()
            if action:
                return action

        if phase in ["started", "continued"]:
            return "ask_user"

        return "reply"

    def phase_updates(
        self,
        config: Dict[str, Any],
        phase: str,
        rule: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        updates: Dict[str, Any] = {}

        phase_updates = config.get("phase_updates", {})
        if isinstance(phase_updates, dict) and isinstance(phase_updates.get(phase), dict):
            updates.update(phase_updates.get(phase, {}))

        if isinstance(rule, dict):
            rule_phase_updates = rule.get("phase_updates", {})
            if isinstance(rule_phase_updates, dict) and isinstance(rule_phase_updates.get(phase), dict):
                updates.update(rule_phase_updates.get(phase, {}))

        return updates

    def build_note(
        self,
        config: Dict[str, Any],
        phase: str,
        rule: Dict[str, Any],
        extra: Dict[str, Any]
    ) -> str:
        notes = config.get("notes", {})
        if isinstance(notes, dict):
            template = str(notes.get(phase, "") or "").strip()
            if template:
                return render_template(
                    template,
                    {
                        "phase": phase,
                        "rule": rule,
                        "extra": extra
                    }
                )

        rule_id = str(rule.get("id", "") or "").strip() if isinstance(rule, dict) else ""
        if rule_id:
            return f"troubleshooting:{phase}:{rule_id}"

        return f"troubleshooting:{phase}"

    # ------------------------------------------------------------------
    # Rule matching
    # ------------------------------------------------------------------

    def find_matching_rules(
        self,
        config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any],
        variables: Optional[Dict[str, Any]] = None
    ) -> List[Dict[str, Any]]:
        rules = config.get("rules", [])

        if not isinstance(rules, list):
            return []

        matches: List[Dict[str, Any]] = []

        for rule in rules:
            if not isinstance(rule, dict):
                continue

            scored = self.score_rule_with_details(
                rule=rule,
                config=config,
                message=message,
                normalization=normalization,
                variables=variables or {}
            )

            if scored.get("matched"):
                matches.append({
                    "rule": rule,
                    "score": scored.get("score", 0.0),
                    "matched": scored.get("matched", {})
                })

        matches.sort(key=lambda item: float(item.get("score", 0.0) or 0.0), reverse=True)

        max_matches = self.safe_int(config.get("max_matched_rules", 5), 5)
        if max_matches > 0:
            matches = matches[:max_matches]

        return matches

    def find_matching_rule(
        self,
        config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        matches = self.find_matching_rules(
            config=config,
            message=message,
            normalization=normalization
        )
        return matches[0]["rule"] if matches else {}

    def score_rule(
        self,
        rule: Dict[str, Any],
        config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any],
        variables: Optional[Dict[str, Any]] = None
    ) -> float:
        return float(self.score_rule_with_details(
            rule=rule,
            config=config,
            message=message,
            normalization=normalization,
            variables=variables or {}
        ).get("score", 0.0) or 0.0)

    def score_rule_with_details(
        self,
        rule: Dict[str, Any],
        config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> Dict[str, Any]:
        if rule.get("enabled", True) is False:
            return {"matched": {}, "score": 0.0}

        if self.rule_negative_matches(rule, message, normalization):
            return {"matched": {}, "score": 0.0}

        if not self.rule_conditions_match(rule, variables):
            return {"matched": {}, "score": 0.0}

        scoring = config.get("rule_scoring", {})
        if not isinstance(scoring, dict):
            scoring = {}

        phrase_weight = self.safe_float(scoring.get("phrase_weight", 1.0), 1.0)
        regex_weight = self.safe_float(scoring.get("regex_weight", 1.25), 1.25)
        required_weight = self.safe_float(scoring.get("required_condition_weight", 0.25), 0.25)
        rule_weight = self.safe_float(rule.get("weight", rule.get("priority_weight", 0.0)), 0.0)

        score = 0.0
        matched: Dict[str, Any] = {}

        phrases = self.flatten_phrase_sources([
            rule.get("phrases", []),
            rule.get("symptoms", []),
            rule.get("keywords", [])
        ])

        matched_phrases: List[str] = []
        if phrases:
            for phrase in phrases:
                if matches_any(message, [phrase], normalization):
                    matched_phrases.append(str(phrase))
            if matched_phrases:
                score += phrase_weight * len(matched_phrases)
                matched["phrases"] = matched_phrases

        regex_matches = self.match_regexes(message, self.config_list(rule, "regex_patterns") + self.config_list(rule, "patterns"))
        if regex_matches:
            score += regex_weight * len(regex_matches)
            matched["regex"] = regex_matches

        if self.rule_required_paths_match(rule, variables):
            score += required_weight

        score += rule_weight

        min_score = self.safe_float(rule.get("min_score", config.get("min_rule_score", 0.1)), 0.1)

        if score < min_score:
            return {"matched": {}, "score": 0.0}

        return {
            "matched": matched,
            "score": score
        }

    def rule_matches(
        self,
        rule: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> bool:
        return bool(
            self.score_rule_with_details(
                rule=rule,
                config={},
                message=message,
                normalization=normalization,
                variables={}
            ).get("matched")
        )

    def rule_negative_matches(self, rule: Dict[str, Any], message: str, normalization: Dict[str, Any]) -> bool:
        negative_phrases = self.flatten_phrase_sources([
            rule.get("negative_phrases", []),
            rule.get("exclude_phrases", []),
            rule.get("not_phrases", [])
        ])

        if negative_phrases and matches_any(message, negative_phrases, normalization):
            return True

        negative_patterns = self.config_list(rule, "negative_regex_patterns") + self.config_list(rule, "exclude_patterns")
        return bool(self.match_regexes(message, negative_patterns))

    def rule_conditions_match(self, rule: Dict[str, Any], variables: Dict[str, Any]) -> bool:
        conditions = rule.get("conditions", [])
        if isinstance(conditions, list):
            for condition in conditions:
                if not self.condition_matches(condition, variables):
                    return False

        return True

    def rule_required_paths_match(self, rule: Dict[str, Any], variables: Dict[str, Any]) -> bool:
        required_paths = self.config_list(rule, "required_paths")

        for path in required_paths:
            if deep_get(variables, str(path or "").strip()) in [None, "", [], {}]:
                return False

        missing_paths = self.config_list(rule, "missing_paths")

        for path in missing_paths:
            if deep_get(variables, str(path or "").strip()) not in [None, "", [], {}]:
                return False

        return True

    def match_regexes(self, message: str, patterns: List[Any]) -> List[str]:
        matches: List[str] = []

        for pattern_item in patterns:
            if isinstance(pattern_item, dict):
                pattern = str(pattern_item.get("regex", "") or "")
            else:
                pattern = str(pattern_item or "")

            if not pattern:
                continue

            try:
                match = re.search(pattern, message or "", flags=re.IGNORECASE)
            except re.error:
                continue

            if match:
                matches.append(match.group(0))

        return matches

    def find_rule(self, config: Dict[str, Any], rule_id: str) -> Dict[str, Any]:
        for rule in config.get("rules", []) or []:
            if not isinstance(rule, dict):
                continue

            if str(rule.get("id", "") or "") == str(rule_id or ""):
                return rule

        return {}

    # ------------------------------------------------------------------
    # Conditions / helpers
    # ------------------------------------------------------------------

    def condition_matches(
        self,
        condition: Any,
        variables: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> bool:
        if not isinstance(condition, dict):
            return False

        context = context or {"variables": variables}

        if "all" in condition:
            return all(
                self.condition_matches(item, variables, context=context)
                for item in self.config_list(condition, "all")
                if isinstance(item, dict)
            )

        if "any" in condition:
            return any(
                self.condition_matches(item, variables, context=context)
                for item in self.config_list(condition, "any")
                if isinstance(item, dict)
            )

        if "not" in condition and isinstance(condition.get("not"), dict):
            return not self.condition_matches(condition.get("not"), variables, context=context)

        path = str(condition.get("path", "") or "").strip()

        if path:
            if path.startswith("context."):
                value = deep_get(context, path[len("context."):])
            else:
                value = deep_get(variables, path)
        else:
            value = None

        exists = value not in [None, "", [], {}]

        if condition.get("exists") is True and not exists:
            return False

        if condition.get("exists") is False and exists:
            return False

        if "equals" in condition and value != condition.get("equals"):
            return False

        if "not_equals" in condition and value == condition.get("not_equals"):
            return False

        if isinstance(condition.get("in"), list) and value not in condition.get("in"):
            return False

        if isinstance(condition.get("not_in"), list) and value in condition.get("not_in"):
            return False

        if condition.get("truthy") is True and not bool(value):
            return False

        if condition.get("falsy") is True and bool(value):
            return False

        if "contains" in condition and str(condition.get("contains")) not in str(value or ""):
            return False

        if "regex" in condition:
            try:
                if not re.search(str(condition.get("regex") or ""), str(value or ""), flags=re.IGNORECASE):
                    return False
            except re.error:
                return False

        return True

    def get_active_state_values(self, config: Dict[str, Any]) -> List[str]:
        configured = config.get("active_state_values", [])
        if isinstance(configured, list) and configured:
            return [str(item) for item in configured]

        active_state = str(config.get("active_state", "active") or "active")
        return [active_state]

    @staticmethod
    def config_path(config: Dict[str, Any], path: str, default: Any = None) -> Any:
        current: Any = config

        for part in str(path or "").split("."):
            if not part:
                continue

            if not isinstance(current, dict):
                return default

            if part not in current:
                return default

            current = current.get(part)

        return current if current is not None else default

    @staticmethod
    def config_list(config: Dict[str, Any], path: str) -> List[Any]:
        value = TroubleshootingSubagent.config_path(config, path, [])

        if isinstance(value, list):
            return value

        if value in [None, ""]:
            return []

        return [value]

    @staticmethod
    def config_dict(config: Dict[str, Any], path: str) -> Dict[str, Any]:
        value = TroubleshootingSubagent.config_path(config, path, {})

        return value if isinstance(value, dict) else {}

    @staticmethod
    def flatten_phrase_sources(sources: List[Any]) -> List[Any]:
        phrases: List[Any] = []

        for source in sources:
            if isinstance(source, list):
                phrases.extend(source)
            elif source not in [None, "", [], {}]:
                phrases.append(source)

        return phrases

    @staticmethod
    def safe_int(value: Any, default: int) -> int:
        try:
            return int(value)
        except Exception:
            return default

    @staticmethod
    def safe_float(value: Any, default: float) -> float:
        try:
            return float(value)
        except Exception:
            return default

    @staticmethod
    def get_config_bool(config: Dict[str, Any], path: str, default: bool = False) -> bool:
        value = TroubleshootingSubagent.config_path(config, path, default)

        if isinstance(value, bool):
            return value

        if value is None:
            return default

        return str(value).strip().lower() in ["1", "true", "yes", "y", "on"]
