from typing import Any, Dict, List, Optional

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_variable_patch,
    deep_get,
    get_subagent_config,
    matches_any,
    render_template
)


class TroubleshootingSubagent:
    """
    Troubleshooting executor for the LangGraph architecture.

    Responsibilities:
    - detect problem/service category from configured rules
    - maintain lightweight state using configured paths
    - update safe variables and rule metadata using configured mappings
    - return internal labels/draft signals only

    Not responsible for final customer-facing wording.
    Final diagnostic wording is generated by graph.response_node and validated by quality_guard.
    """

    name = "troubleshooting"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {}) or {}

        if self.should_not_take_over(context, config, normalization):
            return SubagentResult(handled=False)

        if self.should_skip_due_to_existing_paths(config, variables):
            return SubagentResult(handled=False)

        active_result = self.continue_active_troubleshooting_if_any(
            context=context,
            config=config,
            variables=variables
        )

        if active_result.handled:
            return active_result

        matched_rule = self.find_matching_rule(
            config=config,
            message=context.user_message,
            normalization=normalization
        )

        if not matched_rule:
            return SubagentResult(handled=False)

        return self.start_rule(
            context=context,
            config=config,
            variables=variables,
            rule=matched_rule
        )

    def should_not_take_over(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        """
        Decide whether another configured flow should own the turn.

        All takeover/blocking phrases are read from config. This keeps this
        executor generic and prevents domain phrases from living in Python.
        """
        takeover_config = config.get("do_not_take_over", {})
        if not isinstance(takeover_config, dict):
            takeover_config = {}

        phrase_sources: List[Any] = [
            config.get("direct_booking_phrases", []),
            takeover_config.get("phrases", []),
            takeover_config.get("intent_phrases", []),
        ]

        phrases: List[str] = []
        for source in phrase_sources:
            if isinstance(source, list):
                phrases.extend([str(item or "") for item in source if str(item or "").strip()])

        if phrases and matches_any(context.user_message, phrases, normalization):
            return True

        variable_conditions = takeover_config.get("variable_conditions", [])
        if isinstance(variable_conditions, list):
            for condition in variable_conditions:
                if self.condition_matches(condition, context.variables or {}):
                    return True

        return False

    def should_skip_due_to_existing_paths(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        for path in config.get("skip_if_paths_exist", []) or []:
            current = deep_get(variables, str(path))

            if current not in [None, "", [], {}]:
                return True

        return False

    def continue_active_troubleshooting_if_any(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> SubagentResult:
        state_path = str(config.get("state_path", "troubleshooting.stage") or "troubleshooting.stage")
        count_path = str(config.get("count_path", "troubleshooting.diagnostic_count") or "troubleshooting.diagnostic_count")
        selected_rule_path = str(config.get("selected_rule_path", "troubleshooting.selected_rule_id") or "troubleshooting.selected_rule_id")

        current_state = str(deep_get(variables, state_path, "") or "").strip()
        selected_rule_id = str(deep_get(variables, selected_rule_path, "") or "").strip()

        if not selected_rule_id:
            return SubagentResult(handled=False)

        active_state_values = self.get_active_state_values(config)

        if current_state not in active_state_values:
            return SubagentResult(handled=False)

        rule = self.find_rule(config, selected_rule_id)

        if not rule:
            return SubagentResult(handled=False)

        current_count = deep_get(variables, count_path, 0)

        try:
            current_count_int = int(current_count or 0)
        except Exception:
            current_count_int = 0

        return self.continue_rule(
            context=context,
            config=config,
            variables=variables,
            rule=rule,
            current_count=current_count_int
        )

    def start_rule(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        rule: Dict[str, Any]
    ) -> SubagentResult:
        state_path = str(config.get("state_path", "troubleshooting.stage") or "troubleshooting.stage")
        count_path = str(config.get("count_path", "troubleshooting.diagnostic_count") or "troubleshooting.diagnostic_count")
        selected_rule_path = str(config.get("selected_rule_path", "troubleshooting.selected_rule_id") or "troubleshooting.selected_rule_id")
        active_state = str(config.get("active_state", "active") or "active")

        updates: Dict[str, Any] = {}

        if isinstance(rule.get("variable_updates"), dict):
            updates.update(rule.get("variable_updates", {}))

        updates.update(self.build_rule_metadata_updates(config, rule, context.user_message))
        updates[state_path] = active_state
        updates[count_path] = 1
        updates[selected_rule_path] = rule.get("id", "")

        clear = rule.get("clear_variables", [])
        if not isinstance(clear, list):
            clear = []

        patched = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=clear
        )

        phase = "started"
        answer = render_template(
            self.rule_label(config, rule, phase),
            {
                "variables": patched,
                "rule": rule,
                "phase": phase,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action=self.phase_action(config, phase),
            answer=answer,
            variable_updates=updates,
            clear_variables=clear,
            selected_subagent=self.name,
            notes=self.build_note(config, phase, rule, {"count": 1})
        )

    def continue_rule(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        rule: Dict[str, Any],
        current_count: int
    ) -> SubagentResult:
        state_path = str(config.get("state_path", "troubleshooting.stage") or "troubleshooting.stage")
        count_path = str(config.get("count_path", "troubleshooting.diagnostic_count") or "troubleshooting.diagnostic_count")
        complete_state = str(config.get("complete_state", "complete") or "complete")
        active_state = str(config.get("active_state", "active") or "active")

        try:
            max_diagnostic_turns = int(config.get("max_diagnostic_turns_before_visit_offer", 2) or 2)
        except Exception:
            max_diagnostic_turns = 2

        next_count = max(0, int(current_count or 0)) + 1

        updates: Dict[str, Any] = {}
        updates[count_path] = next_count
        updates.update(self.build_latest_answer_updates(config, context.user_message))

        if next_count >= max_diagnostic_turns:
            phase = "complete"
            updates[state_path] = complete_state
            inspection_path = str(
                config.get("inspection_recommended_path", "")
                or self.config_path(config, "phase_updates.complete.inspection_recommended_path", "")
                or "troubleshooting.inspection_recommended"
            )
            if inspection_path:
                updates[inspection_path] = True
            updates.update(self.phase_updates(config, phase))
        else:
            phase = "continued"
            updates[state_path] = active_state
            updates.update(self.phase_updates(config, phase))

        patched = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=[]
        )

        answer = render_template(
            self.rule_label(config, rule, phase),
            {
                "variables": patched,
                "rule": rule,
                "phase": phase,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action=self.phase_action(config, phase),
            answer=answer,
            variable_updates=updates,
            clear_variables=[],
            selected_subagent=self.name,
            notes=self.build_note(config, phase, rule, {"count": next_count})
        )

    def build_rule_metadata_updates(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        """
        Build state updates using configured mappings.

        Preferred config:
        metadata_update_mappings: [
          {"target": "troubleshooting.category", "source": "rule.category"},
          {"target": "troubleshooting.last_user_symptom", "source": "message"}
        ]

        A backwards-compatible default mapping is kept so existing bundles
        continue working. The default is operational state, not customer-facing
        wording.
        """
        mappings = config.get("metadata_update_mappings", [])

        if not isinstance(mappings, list) or not mappings:
            base_path = str(config.get("metadata_path", "troubleshooting") or "troubleshooting")
            mappings = [
                {"target": f"{base_path}.last_user_symptom", "source": "message"},
                {"target": f"{base_path}.category", "source": "rule.category"},
                {"target": f"{base_path}.rule_id", "source": "rule.id"},
                {"target": f"{base_path}.expected_system", "source": "rule.expected_system"},
                {"target": f"{base_path}.possible_causes", "source": "rule.possible_causes", "default": []},
                {"target": f"{base_path}.recommended_questions", "source": "rule.recommended_questions", "default": []},
                {"target": f"{base_path}.inspection_recommended", "value": False},
                {"target": f"{base_path}.severity", "source": "rule.severity", "skip_if_empty": True},
                {"target": f"{base_path}.safety_note", "source": "rule.safety_note", "skip_if_empty": True},
            ]

        return self.build_updates_from_mappings(
            mappings=mappings,
            rule=rule,
            message=message,
            variables={}
        )

    def build_latest_answer_updates(
        self,
        config: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        mappings = config.get("latest_answer_update_mappings", [])

        if not isinstance(mappings, list) or not mappings:
            base_path = str(config.get("metadata_path", "troubleshooting") or "troubleshooting")
            mappings = [
                {"target": f"{base_path}.latest_user_answer", "source": "message"}
            ]

        return self.build_updates_from_mappings(
            mappings=mappings,
            rule={},
            message=message,
            variables={}
        )

    def build_updates_from_mappings(
        self,
        mappings: List[Dict[str, Any]],
        rule: Dict[str, Any],
        message: str,
        variables: Dict[str, Any]
    ) -> Dict[str, Any]:
        updates: Dict[str, Any] = {}

        for item in mappings:
            if not isinstance(item, dict):
                continue

            target = str(item.get("target", "") or "").strip()
            if not target:
                continue

            if "value" in item:
                value = item.get("value")
            else:
                value = self.mapping_source_value(
                    source=str(item.get("source", "") or ""),
                    rule=rule,
                    message=message,
                    variables=variables,
                    default=item.get("default")
                )

            if item.get("skip_if_empty", False) and value in [None, "", [], {}]:
                continue

            updates[target] = value

        return updates

    def mapping_source_value(
        self,
        source: str,
        rule: Dict[str, Any],
        message: str,
        variables: Dict[str, Any],
        default: Any = None
    ) -> Any:
        if not source:
            return default

        if source == "message":
            return message

        if source.startswith("rule."):
            return deep_get(rule, source[len("rule."):], default)

        if source.startswith("variables."):
            return deep_get(variables, source[len("variables."):], default)

        return default

    def rule_label(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        phase: str
    ) -> str:
        """
        Return an internal label from config.

        No customer-facing text or domain labels are hardcoded here. Existing
        bundles can still use templates.started/continued/complete/default.
        """
        templates = config.get("templates", {})
        if not isinstance(templates, dict):
            templates = {}

        rule_templates = rule.get("templates", {})
        if not isinstance(rule_templates, dict):
            rule_templates = {}

        phase_template_keys = config.get("phase_template_keys", {})
        if not isinstance(phase_template_keys, dict):
            phase_template_keys = {}

        candidates: List[str] = []

        rule_phase_value = str(rule_templates.get(phase, "") or "").strip()
        if rule_phase_value:
            candidates.append(rule_phase_value)

        phase_key = str(phase_template_keys.get(phase, "") or "").strip()
        if phase_key:
            configured = str(templates.get(phase_key, "") or "").strip()
            candidates.append(configured or phase_key)

        direct_phase_value = str(templates.get(phase, "") or "").strip()
        if direct_phase_value:
            candidates.append(direct_phase_value)

        default_key = str(config.get("default_template_key", "") or "").strip()
        if default_key:
            configured_default = str(templates.get(default_key, "") or "").strip()
            candidates.append(configured_default or default_key)

        configured_default_value = str(templates.get("default", "") or "").strip()
        if configured_default_value:
            candidates.append(configured_default_value)

        fallback_prefix = str(config.get("template_fallback_prefix", self.name) or self.name).strip()
        candidates.append(f"{fallback_prefix}_{phase}".upper())

        for candidate in candidates:
            if candidate:
                return candidate

        return phase.upper()

    def phase_action(self, config: Dict[str, Any], phase: str) -> str:
        actions = config.get("phase_actions", {})
        if isinstance(actions, dict):
            action = str(actions.get(phase, "") or "").strip()
            if action:
                return action

        default_action = str(config.get("default_action", "") or "").strip()
        return default_action or "ask_user"

    def phase_updates(self, config: Dict[str, Any], phase: str) -> Dict[str, Any]:
        phase_updates_config = config.get("phase_updates", {})
        if not isinstance(phase_updates_config, dict):
            return {}

        updates = phase_updates_config.get(phase, {})
        return updates if isinstance(updates, dict) else {}

    def build_note(
        self,
        config: Dict[str, Any],
        phase: str,
        rule: Dict[str, Any],
        extra: Optional[Dict[str, Any]] = None
    ) -> str:
        if not config.get("include_internal_notes", True):
            return ""

        rule_id = str(rule.get("id", "") or "").strip()
        parts = [self.name, phase]

        if rule_id:
            parts.append(rule_id)

        if isinstance(extra, dict):
            for key, value in extra.items():
                if value not in [None, ""]:
                    parts.append(f"{key}={value}")

        return " ".join(parts)

    def find_matching_rule(
        self,
        config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        rules = config.get("rules", [])

        if not isinstance(rules, list):
            return {}

        for rule in rules:
            if not isinstance(rule, dict):
                continue

            if self.rule_matches(rule, message, normalization):
                return rule

        return {}

    def rule_matches(
        self,
        rule: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> bool:
        phrases = rule.get("phrases", [])

        if not isinstance(phrases, list):
            phrases = []

        if phrases and matches_any(message, phrases, normalization):
            return True

        all_required = rule.get("all_required_phrases", [])
        if isinstance(all_required, list) and all_required:
            return all(
                matches_any(message, [phrase], normalization)
                for phrase in all_required
                if str(phrase or "").strip()
            )

        return False

    @staticmethod
    def find_rule(config: Dict[str, Any], rule_id: str) -> Dict[str, Any]:
        rules = config.get("rules", [])

        if not isinstance(rules, list):
            return {}

        for rule in rules:
            if isinstance(rule, dict) and str(rule.get("id", "")) == str(rule_id):
                return rule

        return {}

    def condition_matches(self, condition: Any, variables: Dict[str, Any]) -> bool:
        if not isinstance(condition, dict):
            return False

        path = str(condition.get("path", "") or "").strip()
        if not path:
            return False

        current = deep_get(variables, path)

        if "exists" in condition:
            exists = current not in [None, "", [], {}]
            return exists is bool(condition.get("exists"))

        if "equals" in condition:
            return current == condition.get("equals")

        if "in" in condition and isinstance(condition.get("in"), list):
            return current in condition.get("in", [])

        return current not in [None, "", [], {}]

    def get_active_state_values(self, config: Dict[str, Any]) -> List[str]:
        values = config.get("active_state_values", [])

        if isinstance(values, list) and values:
            return [
                str(item or "").strip()
                for item in values
                if str(item or "").strip()
            ]

        active_state = str(config.get("active_state", "") or "").strip()

        return [active_state] if active_state else []

    @staticmethod
    def config_path(config: Dict[str, Any], path: str, default: Any = None) -> Any:
        current: Any = config

        for part in str(path or "").split("."):
            if not part:
                continue

            if not isinstance(current, dict):
                return default

            current = current.get(part)

            if current is None:
                return default

        return current
