from typing import Any, Dict

from app.subagents.base import (
    SubagentContext,
    SubagentResult,
    apply_variable_patch,
    deep_get,
    get_subagent_config,
    matches_any,
    render_template
)


class TroubleshootingSubagent:
    """
    Troubleshooting executor for the LangGraph architecture.

    Responsibilities:
    - detect service/problem category from configured rules
    - maintain lightweight troubleshooting state
    - update safe variables like service_needed and troubleshooting metadata
    - return an internal label/draft signal

    Not responsible for final diagnostic wording.
    The final customer-facing troubleshooting explanation is generated by
    graph.response_node and validated by quality_guard.
    """

    name = "troubleshooting"

    def get_config(self, assistant_config: Dict[str, Any]) -> Dict[str, Any]:
        return get_subagent_config(assistant_config, self.name)

    def run(self, context: SubagentContext) -> SubagentResult:
        config = self.get_config(context.assistant_config)

        if not config.get("enabled", False):
            return SubagentResult(handled=False)

        variables = dict(context.variables or {})
        normalization = context.assistant_config.get("normalization", {})

        if self.should_not_take_over_booking(context, config, normalization):
            return SubagentResult(handled=False)

        if self.should_skip_due_to_existing_paths(config, variables):
            return SubagentResult(handled=False)

        active_result = self.continue_active_troubleshooting_if_any(
            context=context,
            config=config,
            variables=variables
        )

        if active_result.handled:
            return active_result

        matched_rule = self.find_matching_rule(
            config=config,
            message=context.user_message,
            normalization=normalization
        )

        if not matched_rule:
            return SubagentResult(handled=False)

        return self.start_rule(
            context=context,
            config=config,
            variables=variables,
            rule=matched_rule
        )

    def should_not_take_over_booking(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        normalization: Dict[str, Any]
    ) -> bool:
        return matches_any(
            context.user_message,
            config.get("direct_booking_phrases", []),
            normalization
        )

    def should_skip_due_to_existing_paths(
        self,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> bool:
        for path in config.get("skip_if_paths_exist", []):
            current = deep_get(variables, path)

            if current not in [None, "", [], {}]:
                return True

        return False

    def continue_active_troubleshooting_if_any(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any]
    ) -> SubagentResult:
        state_path = config.get("state_path", "troubleshooting.stage")
        count_path = config.get("count_path", "troubleshooting.diagnostic_count")
        selected_rule_path = config.get("selected_rule_path", "troubleshooting.selected_rule_id")
        active_state = config.get("active_state", "active")

        current_state = deep_get(variables, state_path, "")
        selected_rule_id = deep_get(variables, selected_rule_path, "")

        if current_state != active_state or not selected_rule_id:
            return SubagentResult(handled=False)

        rule = self.find_rule(config, selected_rule_id)

        if not rule:
            return SubagentResult(handled=False)

        current_count = deep_get(variables, count_path, 0)

        try:
            current_count_int = int(current_count or 0)
        except Exception:
            current_count_int = 0

        return self.continue_rule(
            context=context,
            config=config,
            variables=variables,
            rule=rule,
            current_count=current_count_int
        )

    def start_rule(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        rule: Dict[str, Any]
    ) -> SubagentResult:
        state_path = config.get("state_path", "troubleshooting.stage")
        count_path = config.get("count_path", "troubleshooting.diagnostic_count")
        selected_rule_path = config.get("selected_rule_path", "troubleshooting.selected_rule_id")
        active_state = config.get("active_state", "active")

        updates = {}

        updates.update(rule.get("variable_updates", {}))
        updates.update(self.build_rule_metadata_updates(config, rule, context.user_message))
        updates[state_path] = active_state
        updates[count_path] = 1
        updates[selected_rule_path] = rule.get("id", "")

        clear = rule.get("clear_variables", [])

        patched = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=clear
        )

        answer = render_template(
            self.rule_label(config, rule, "started"),
            {
                "variables": patched,
                "rule": rule,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="ask_user",
            answer=answer,
            variable_updates=updates,
            clear_variables=clear,
            selected_subagent=self.name,
            notes=f"started troubleshooting rule {rule.get('id', '')}"
        )

    def continue_rule(
        self,
        context: SubagentContext,
        config: Dict[str, Any],
        variables: Dict[str, Any],
        rule: Dict[str, Any],
        current_count: int
    ) -> SubagentResult:
        state_path = config.get("state_path", "troubleshooting.stage")
        count_path = config.get("count_path", "troubleshooting.diagnostic_count")
        complete_state = config.get("complete_state", "complete")
        max_diagnostic_turns = int(config.get("max_diagnostic_turns_before_visit_offer", 2))

        next_count = current_count + 1

        updates = {}
        updates[count_path] = next_count
        updates.update(self.build_latest_answer_updates(config, context.user_message))

        if next_count >= max_diagnostic_turns:
            updates[state_path] = complete_state
            updates[config.get("inspection_recommended_path", "troubleshooting.inspection_recommended")] = True
        else:
            updates[state_path] = config.get("active_state", "active")

        patched = apply_variable_patch(
            variables=variables,
            updates=updates,
            clear=[]
        )

        phase = "complete" if updates.get(state_path) == complete_state else "continued"

        answer = render_template(
            self.rule_label(config, rule, phase),
            {
                "variables": patched,
                "rule": rule,
                "message": context.user_message
            }
        )

        return SubagentResult(
            handled=True,
            action="ask_user",
            answer=answer,
            variable_updates=updates,
            clear_variables=[],
            selected_subagent=self.name,
            notes=f"{phase} troubleshooting rule {rule.get('id', '')} count {next_count}"
        )

    def build_rule_metadata_updates(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        base_path = config.get("metadata_path", "troubleshooting")

        updates = {
            f"{base_path}.last_user_symptom": message,
            f"{base_path}.category": rule.get("category", ""),
            f"{base_path}.rule_id": rule.get("id", ""),
            f"{base_path}.expected_system": rule.get("expected_system", ""),
            f"{base_path}.possible_causes": rule.get("possible_causes", []),
            f"{base_path}.recommended_questions": rule.get("recommended_questions", []),
            f"{base_path}.inspection_recommended": False
        }

        if rule.get("severity"):
            updates[f"{base_path}.severity"] = rule.get("severity")

        if rule.get("safety_note"):
            updates[f"{base_path}.safety_note"] = rule.get("safety_note")

        return updates

    def build_latest_answer_updates(
        self,
        config: Dict[str, Any],
        message: str
    ) -> Dict[str, Any]:
        base_path = config.get("metadata_path", "troubleshooting")

        return {
            f"{base_path}.latest_user_answer": message
        }

    def rule_label(
        self,
        config: Dict[str, Any],
        rule: Dict[str, Any],
        phase: str
    ) -> str:
        templates = config.get("templates", {})

        if phase == "started":
            return templates.get("started", "TROUBLESHOOTING_STARTED")

        if phase == "continued":
            return templates.get("continued", "TROUBLESHOOTING_CONTINUED")

        if phase == "complete":
            return templates.get("complete", "TROUBLESHOOTING_READY_TO_RECOMMEND_INSPECTION")

        return templates.get("default", "TROUBLESHOOTING_STATE_UPDATED")

    def find_matching_rule(
        self,
        config: Dict[str, Any],
        message: str,
        normalization: Dict[str, Any]
    ) -> Dict[str, Any]:
        rules = config.get("rules", [])

        if not isinstance(rules, list):
            return {}

        for rule in rules:
            if not isinstance(rule, dict):
                continue

            phrases = rule.get("phrases", [])

            if not isinstance(phrases, list):
                phrases = []

            if matches_any(message, phrases, normalization):
                return rule

        return {}

    @staticmethod
    def find_rule(config: Dict[str, Any], rule_id: str) -> Dict[str, Any]:
        rules = config.get("rules", [])

        if not isinstance(rules, list):
            return {}

        for rule in rules:
            if isinstance(rule, dict) and rule.get("id") == rule_id:
                return rule

        return {}
